package chisel.registry;

import chisel.Chisel;
import chisel.core.VariantFamily;
import chisel.datagen.VariantFamilies;
import net.minecraft.core.Registry;
import net.minecraft.core.RegistrySetBuilder;
import net.minecraft.resources.ResourceKey;

public class ChiselVariants {

    public static final ResourceKey<Registry<VariantFamily>> VARIANT_FAMILY_REGISTRY_KEY = ResourceKey.createRegistryKey(Chisel.prefix("variant_families"));

    public static ResourceKey<VariantFamily> ACACIA = create(VariantFamilies.ACACIA);
    public static ResourceKey<VariantFamily> ALUMINUM = create(VariantFamilies.ALUMINUM);
    public static ResourceKey<VariantFamily> ANDESITE = create(VariantFamilies.ANDESITE);
    public static ResourceKey<VariantFamily> ANTIBLOCK = create(VariantFamilies.ANTIBLOCK);
    public static ResourceKey<VariantFamily> BIRCH = create(VariantFamilies.BIRCH);
    public static ResourceKey<VariantFamily> BOOKSHELF = create(VariantFamilies.BOOKSHELF);
    public static ResourceKey<VariantFamily> BRICKS = create(VariantFamilies.BRICKS);
    public static ResourceKey<VariantFamily> BRONZE = create(VariantFamilies.BRONZE);
    public static ResourceKey<VariantFamily> CARPET = create(VariantFamilies.CARPET);
    public static ResourceKey<VariantFamily> CARPET_FLOOR = create(VariantFamilies.CARPET_FLOOR);
    public static ResourceKey<VariantFamily> CLOUD = create(VariantFamilies.CLOUD);
    public static ResourceKey<VariantFamily> COBBLESTONE = create(VariantFamilies.COBBLESTONE);
    public static ResourceKey<VariantFamily> CONCRETE = create(VariantFamilies.CONCRETE);
    public static ResourceKey<VariantFamily> COPPER = create(VariantFamilies.COPPER);
    public static ResourceKey<VariantFamily> DARK_OAK = create(VariantFamilies.DARK_OAK);
    public static ResourceKey<VariantFamily> DIAMOND = create(VariantFamilies.DIAMOND);
    public static ResourceKey<VariantFamily> DIORITE = create(VariantFamilies.DIORITE);
    public static ResourceKey<VariantFamily> DIRT = create(VariantFamilies.DIRT);
    public static ResourceKey<VariantFamily> EMERALD = create(VariantFamilies.EMERALD);
    public static ResourceKey<VariantFamily> ENERGIZED_VOIDSTONE = create(VariantFamilies.ENERGIZED_VOIDSTONE);
    public static ResourceKey<VariantFamily> FACTORY = create(VariantFamilies.FACTORY);
    public static ResourceKey<VariantFamily> FUTURA = create(VariantFamilies.FUTURA);
    public static ResourceKey<VariantFamily> GLASS = create(VariantFamilies.GLASS);
    public static ResourceKey<VariantFamily> GLASS_PANE = create(VariantFamilies.GLASS_PANE);
    public static ResourceKey<VariantFamily> GLOWSTONE = create(VariantFamilies.GLOWSTONE);
    public static ResourceKey<VariantFamily> GOLD = create(VariantFamilies.GOLD);
    public static ResourceKey<VariantFamily> GRANITE = create(VariantFamilies.GRANITE);
    public static ResourceKey<VariantFamily> GRIMSTONE = create(VariantFamilies.GRIMSTONE);
    public static ResourceKey<VariantFamily> HEX_PLATING = create(VariantFamilies.HEX_PLATING);
    public static ResourceKey<VariantFamily> HOLYSTONE = create(VariantFamilies.HOLYSTONE);
    public static ResourceKey<VariantFamily> ICE = create(VariantFamilies.ICE);
    public static ResourceKey<VariantFamily> IRON = create(VariantFamilies.IRON);
    public static ResourceKey<VariantFamily> IRON_BARS = create(VariantFamilies.IRON_BARS);
    public static ResourceKey<VariantFamily> JUNGLE = create(VariantFamilies.JUNGLE);
    public static ResourceKey<VariantFamily> LABORATORY = create(VariantFamilies.LABORATORY);
    public static ResourceKey<VariantFamily> LAPIS = create(VariantFamilies.LAPIS);
    public static ResourceKey<VariantFamily> LARGE_HEX_PLATING = create(VariantFamilies.LARGE_HEX_PLATING);
    public static ResourceKey<VariantFamily> LAVASTONE = create(VariantFamilies.LAVASTONE);
    public static ResourceKey<VariantFamily> LEAD = create(VariantFamilies.LEAD);
    public static ResourceKey<VariantFamily> LEAF = create(VariantFamilies.LEAF);
    public static ResourceKey<VariantFamily> LIMESTONE = create(VariantFamilies.LIMESTONE);
    public static ResourceKey<VariantFamily> LIT_PUMPKIN = create(VariantFamilies.LIT_PUMPKIN);
    public static ResourceKey<VariantFamily> MARBLE = create(VariantFamilies.MARBLE);
    public static ResourceKey<VariantFamily> MOSSY_COBBLESTONE = create(VariantFamilies.MOSSY_COBBLESTONE);
    public static ResourceKey<VariantFamily> MOSSY_TEMPLE = create(VariantFamilies.MOSSY_TEMPLE);
    public static ResourceKey<VariantFamily> NETHERBRICK = create(VariantFamilies.NETHERBRICK);
    public static ResourceKey<VariantFamily> NETHERRACK = create(VariantFamilies.NETHERRACK);
    public static ResourceKey<VariantFamily> OAK = create(VariantFamilies.OAK);
    public static ResourceKey<VariantFamily> OBSIDIAN = create(VariantFamilies.OBSIDIAN);
    public static ResourceKey<VariantFamily> PACKED_ICE = create(VariantFamilies.PACKED_ICE);
    public static ResourceKey<VariantFamily> PACKED_ICE_PILLAR = create(VariantFamilies.PACKED_ICE_PILLAR);
    public static ResourceKey<VariantFamily> PAPERWALL = create(VariantFamilies.PAPERWALL);
    public static ResourceKey<VariantFamily> PAPERWALL_BLOCK = create(VariantFamilies.PAPERWALL_BLOCK);
    public static ResourceKey<VariantFamily> PUMPKIN = create(VariantFamilies.PUMPKIN);
    public static ResourceKey<VariantFamily> REDSTONE = create(VariantFamilies.REDSTONE);
    public static ResourceKey<VariantFamily> ROAD_LINE = create(VariantFamilies.ROAD_LINE);
    public static ResourceKey<VariantFamily> RUNIC_VOIDSTONE = create(VariantFamilies.RUNIC_VOIDSTONE);
    public static ResourceKey<VariantFamily> SANDSTONE = create(VariantFamilies.SANDSTONE);
    public static ResourceKey<VariantFamily> SILVER = create(VariantFamilies.SILVER);
    public static ResourceKey<VariantFamily> SPRUCE = create(VariantFamilies.SPRUCE);
    public static ResourceKey<VariantFamily> SNAKESTONE_SAND = create(VariantFamilies.SNAKESTONE_SAND);
    public static ResourceKey<VariantFamily> SNAKESTONE_STONE = create(VariantFamilies.SNAKESTONE_STONE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_BLACK = create(VariantFamilies.STAINED_GLASS_BLACK);
    public static ResourceKey<VariantFamily> STAINED_GLASS_BLUE = create(VariantFamilies.STAINED_GLASS_BLUE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_BROWN = create(VariantFamilies.STAINED_GLASS_BROWN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_CYAN = create(VariantFamilies.STAINED_GLASS_CYAN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_GRAY = create(VariantFamilies.STAINED_GLASS_GRAY);
    public static ResourceKey<VariantFamily> STAINED_GLASS_GREEN = create(VariantFamilies.STAINED_GLASS_GREEN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_LIGHT_BLUE = create(VariantFamilies.STAINED_GLASS_LIGHT_BLUE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_LIGHT_GRAY = create(VariantFamilies.STAINED_GLASS_LIGHT_GRAY);
    public static ResourceKey<VariantFamily> STAINED_GLASS_LIME = create(VariantFamilies.STAINED_GLASS_LIME);
    public static ResourceKey<VariantFamily> STAINED_GLASS_MAGENTA = create(VariantFamilies.STAINED_GLASS_MAGENTA);
    public static ResourceKey<VariantFamily> STAINED_GLASS_ORANGE = create(VariantFamilies.STAINED_GLASS_ORANGE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PINK = create(VariantFamilies.STAINED_GLASS_PINK);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PURPLE = create(VariantFamilies.STAINED_GLASS_PURPLE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_RED = create(VariantFamilies.STAINED_GLASS_RED);
    public static ResourceKey<VariantFamily> STAINED_GLASS_WHITE = create(VariantFamilies.STAINED_GLASS_WHITE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_YELLOW = create(VariantFamilies.STAINED_GLASS_YELLOW);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_BLACK = create(VariantFamilies.STAINED_GLASS_PANE_BLACK);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_BLUE = create(VariantFamilies.STAINED_GLASS_PANE_BLUE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_BROWN = create(VariantFamilies.STAINED_GLASS_PANE_BROWN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_CYAN = create(VariantFamilies.STAINED_GLASS_PANE_CYAN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_GRAY = create(VariantFamilies.STAINED_GLASS_PANE_GRAY);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_GREEN = create(VariantFamilies.STAINED_GLASS_PANE_GREEN);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_LIGHT_BLUE = create(VariantFamilies.STAINED_GLASS_PANE_LIGHT_BLUE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_LIGHT_GRAY = create(VariantFamilies.STAINED_GLASS_PANE_LIGHT_GRAY);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_LIME = create(VariantFamilies.STAINED_GLASS_PANE_LIME);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_MAGENTA = create(VariantFamilies.STAINED_GLASS_PANE_MAGENTA);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_ORANGE = create(VariantFamilies.STAINED_GLASS_PANE_ORANGE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_PINK = create(VariantFamilies.STAINED_GLASS_PANE_PINK);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_PURPLE = create(VariantFamilies.STAINED_GLASS_PANE_PURPLE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_RED = create(VariantFamilies.STAINED_GLASS_PANE_RED);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_WHITE = create(VariantFamilies.STAINED_GLASS_PANE_WHITE);
    public static ResourceKey<VariantFamily> STAINED_GLASS_PANE_YELLOW = create(VariantFamilies.STAINED_GLASS_PANE_YELLOW);
    public static ResourceKey<VariantFamily> STEEL = create(VariantFamilies.STEEL);
    public static ResourceKey<VariantFamily> STONE_BRICKS = create(VariantFamilies.STONE_BRICKS);
    public static ResourceKey<VariantFamily> TECHNICAL = create(VariantFamilies.TECHNICAL);
    public static ResourceKey<VariantFamily> TEMPLE = create(VariantFamilies.TEMPLE);
    public static ResourceKey<VariantFamily> TIN = create(VariantFamilies.TIN);
    public static ResourceKey<VariantFamily> TORCH = create(VariantFamilies.TORCH);
    public static ResourceKey<VariantFamily> TYRIAN = create(VariantFamilies.TYRIAN);
    public static ResourceKey<VariantFamily> URANIUM = create(VariantFamilies.URANIUM);
    public static ResourceKey<VariantFamily> VALENTINES = create(VariantFamilies.VALENTINES);
    public static ResourceKey<VariantFamily> VOIDSTONE = create(VariantFamilies.VOIDSTONE);
    public static ResourceKey<VariantFamily> WARNING = create(VariantFamilies.WARNING);
    public static ResourceKey<VariantFamily> WATERSTONE = create(VariantFamilies.WATERSTONE);
    public static ResourceKey<VariantFamily> WOOLEN_CLAY = create(VariantFamilies.WOOLEN_CLAY);

    private static ResourceKey<VariantFamily> create(VariantFamily family) {
        return ResourceKey.create(VARIANT_FAMILY_REGISTRY_KEY, Chisel.prefix(family.getPrefix()));
    }

    public static final RegistrySetBuilder BUILDER = new RegistrySetBuilder()
            .add(VARIANT_FAMILY_REGISTRY_KEY, bootstrap -> {
                bootstrap.register(ACACIA, VariantFamilies.ACACIA);
                bootstrap.register(ALUMINUM, VariantFamilies.ALUMINUM);
                bootstrap.register(ANDESITE, VariantFamilies.ANDESITE);
                bootstrap.register(ANTIBLOCK, VariantFamilies.ANTIBLOCK);
                bootstrap.register(BIRCH, VariantFamilies.BIRCH);
                bootstrap.register(BOOKSHELF, VariantFamilies.BOOKSHELF);
                bootstrap.register(BRICKS, VariantFamilies.BRICKS);
                bootstrap.register(BRONZE, VariantFamilies.BRONZE);
                bootstrap.register(CARPET, VariantFamilies.CARPET);
                bootstrap.register(CARPET_FLOOR, VariantFamilies.CARPET_FLOOR);
                bootstrap.register(CLOUD, VariantFamilies.CLOUD);
                bootstrap.register(COBBLESTONE, VariantFamilies.COBBLESTONE);
                bootstrap.register(CONCRETE, VariantFamilies.CONCRETE);
                bootstrap.register(COPPER, VariantFamilies.COPPER);
                bootstrap.register(DARK_OAK, VariantFamilies.DARK_OAK);
                bootstrap.register(DIAMOND, VariantFamilies.DIAMOND);
                bootstrap.register(DIORITE, VariantFamilies.DIORITE);
                bootstrap.register(DIRT, VariantFamilies.DIRT);
                bootstrap.register(EMERALD, VariantFamilies.EMERALD);
                bootstrap.register(ENERGIZED_VOIDSTONE, VariantFamilies.ENERGIZED_VOIDSTONE);
                bootstrap.register(FACTORY, VariantFamilies.FACTORY);
                bootstrap.register(FUTURA, VariantFamilies.FUTURA);
                bootstrap.register(GLASS, VariantFamilies.GLASS);
                bootstrap.register(GLASS_PANE, VariantFamilies.GLASS_PANE);
                bootstrap.register(GLOWSTONE, VariantFamilies.GLOWSTONE);
                bootstrap.register(GOLD, VariantFamilies.GOLD);
                bootstrap.register(GRANITE, VariantFamilies.GRANITE);
                bootstrap.register(GRIMSTONE, VariantFamilies.GRIMSTONE);
                bootstrap.register(HEX_PLATING, VariantFamilies.HEX_PLATING);
                bootstrap.register(HOLYSTONE, VariantFamilies.HOLYSTONE);
                bootstrap.register(ICE, VariantFamilies.ICE);
                bootstrap.register(IRON, VariantFamilies.IRON);
                bootstrap.register(IRON_BARS, VariantFamilies.IRON_BARS);
                bootstrap.register(JUNGLE, VariantFamilies.JUNGLE);
                bootstrap.register(LABORATORY, VariantFamilies.LABORATORY);
                bootstrap.register(LAPIS, VariantFamilies.LAPIS);
                bootstrap.register(LARGE_HEX_PLATING, VariantFamilies.LARGE_HEX_PLATING);
                bootstrap.register(LAVASTONE, VariantFamilies.LAVASTONE);
                bootstrap.register(LEAD, VariantFamilies.LEAD);
                bootstrap.register(LEAF, VariantFamilies.LEAF);
                bootstrap.register(LIMESTONE, VariantFamilies.LIMESTONE);
                bootstrap.register(LIT_PUMPKIN, VariantFamilies.LIT_PUMPKIN);
                bootstrap.register(MARBLE, VariantFamilies.MARBLE);
                bootstrap.register(MOSSY_COBBLESTONE, VariantFamilies.MOSSY_COBBLESTONE);
                bootstrap.register(MOSSY_TEMPLE, VariantFamilies.MOSSY_TEMPLE);
                bootstrap.register(NETHERBRICK, VariantFamilies.NETHERBRICK);
                bootstrap.register(NETHERRACK, VariantFamilies.NETHERRACK);
                bootstrap.register(OAK, VariantFamilies.OAK);
                bootstrap.register(OBSIDIAN, VariantFamilies.OBSIDIAN);
                bootstrap.register(PACKED_ICE, VariantFamilies.PACKED_ICE);
                bootstrap.register(PACKED_ICE_PILLAR, VariantFamilies.PACKED_ICE_PILLAR);
                bootstrap.register(PAPERWALL, VariantFamilies.PAPERWALL);
                bootstrap.register(PAPERWALL_BLOCK, VariantFamilies.PAPERWALL_BLOCK);
                bootstrap.register(PUMPKIN, VariantFamilies.PUMPKIN);
                bootstrap.register(REDSTONE, VariantFamilies.REDSTONE);
                bootstrap.register(ROAD_LINE, VariantFamilies.ROAD_LINE);
                bootstrap.register(RUNIC_VOIDSTONE, VariantFamilies.RUNIC_VOIDSTONE);
                bootstrap.register(SANDSTONE, VariantFamilies.SANDSTONE);
                bootstrap.register(SILVER, VariantFamilies.SILVER);
                bootstrap.register(SPRUCE, VariantFamilies.SPRUCE);
                bootstrap.register(SNAKESTONE_SAND, VariantFamilies.SNAKESTONE_SAND);
                bootstrap.register(SNAKESTONE_STONE, VariantFamilies.SNAKESTONE_STONE);
                bootstrap.register(STAINED_GLASS_BLACK, VariantFamilies.STAINED_GLASS_BLACK);
                bootstrap.register(STAINED_GLASS_BLUE, VariantFamilies.STAINED_GLASS_BLUE);
                bootstrap.register(STAINED_GLASS_BROWN, VariantFamilies.STAINED_GLASS_BROWN);
                bootstrap.register(STAINED_GLASS_CYAN, VariantFamilies.STAINED_GLASS_CYAN);
                bootstrap.register(STAINED_GLASS_GRAY, VariantFamilies.STAINED_GLASS_GRAY);
                bootstrap.register(STAINED_GLASS_GREEN, VariantFamilies.STAINED_GLASS_GREEN);
                bootstrap.register(STAINED_GLASS_LIGHT_BLUE, VariantFamilies.STAINED_GLASS_LIGHT_BLUE);
                bootstrap.register(STAINED_GLASS_LIGHT_GRAY, VariantFamilies.STAINED_GLASS_LIGHT_GRAY);
                bootstrap.register(STAINED_GLASS_LIME, VariantFamilies.STAINED_GLASS_LIME);
                bootstrap.register(STAINED_GLASS_MAGENTA, VariantFamilies.STAINED_GLASS_MAGENTA);
                bootstrap.register(STAINED_GLASS_ORANGE, VariantFamilies.STAINED_GLASS_ORANGE);
                bootstrap.register(STAINED_GLASS_PINK, VariantFamilies.STAINED_GLASS_PINK);
                bootstrap.register(STAINED_GLASS_PURPLE, VariantFamilies.STAINED_GLASS_PURPLE);
                bootstrap.register(STAINED_GLASS_RED, VariantFamilies.STAINED_GLASS_RED);
                bootstrap.register(STAINED_GLASS_WHITE, VariantFamilies.STAINED_GLASS_WHITE);
                bootstrap.register(STAINED_GLASS_YELLOW, VariantFamilies.STAINED_GLASS_YELLOW);
                bootstrap.register(STAINED_GLASS_PANE_BLACK, VariantFamilies.STAINED_GLASS_PANE_BLACK);
                bootstrap.register(STAINED_GLASS_PANE_BLUE, VariantFamilies.STAINED_GLASS_PANE_BLUE);
                bootstrap.register(STAINED_GLASS_PANE_BROWN, VariantFamilies.STAINED_GLASS_PANE_BROWN);
                bootstrap.register(STAINED_GLASS_PANE_CYAN, VariantFamilies.STAINED_GLASS_PANE_CYAN);
                bootstrap.register(STAINED_GLASS_PANE_GRAY, VariantFamilies.STAINED_GLASS_PANE_GRAY);
                bootstrap.register(STAINED_GLASS_PANE_GREEN, VariantFamilies.STAINED_GLASS_PANE_GREEN);
                bootstrap.register(STAINED_GLASS_PANE_LIGHT_BLUE, VariantFamilies.STAINED_GLASS_PANE_LIGHT_BLUE);
                bootstrap.register(STAINED_GLASS_PANE_LIGHT_GRAY, VariantFamilies.STAINED_GLASS_PANE_LIGHT_GRAY);
                bootstrap.register(STAINED_GLASS_PANE_LIME, VariantFamilies.STAINED_GLASS_PANE_LIME);
                bootstrap.register(STAINED_GLASS_PANE_MAGENTA, VariantFamilies.STAINED_GLASS_PANE_MAGENTA);
                bootstrap.register(STAINED_GLASS_PANE_ORANGE, VariantFamilies.STAINED_GLASS_PANE_ORANGE);
                bootstrap.register(STAINED_GLASS_PANE_PINK, VariantFamilies.STAINED_GLASS_PANE_PINK);
                bootstrap.register(STAINED_GLASS_PANE_PURPLE, VariantFamilies.STAINED_GLASS_PANE_PURPLE);
                bootstrap.register(STAINED_GLASS_PANE_RED, VariantFamilies.STAINED_GLASS_PANE_RED);
                bootstrap.register(STAINED_GLASS_PANE_WHITE, VariantFamilies.STAINED_GLASS_PANE_WHITE);
                bootstrap.register(STAINED_GLASS_PANE_YELLOW, VariantFamilies.STAINED_GLASS_PANE_YELLOW);
                bootstrap.register(STEEL, VariantFamilies.STEEL);
                bootstrap.register(STONE_BRICKS, VariantFamilies.STONE_BRICKS);
                bootstrap.register(TECHNICAL, VariantFamilies.TECHNICAL);
                bootstrap.register(TEMPLE, VariantFamilies.TEMPLE);
                bootstrap.register(TIN, VariantFamilies.TIN);
                bootstrap.register(TORCH, VariantFamilies.TORCH);
                bootstrap.register(TYRIAN, VariantFamilies.TYRIAN);
                bootstrap.register(URANIUM, VariantFamilies.URANIUM);
                bootstrap.register(VALENTINES, VariantFamilies.VALENTINES);
                bootstrap.register(VOIDSTONE, VariantFamilies.VOIDSTONE);
                bootstrap.register(WARNING, VariantFamilies.WARNING);
                bootstrap.register(WATERSTONE, VariantFamilies.WATERSTONE);
                bootstrap.register(WOOLEN_CLAY, VariantFamilies.WOOLEN_CLAY);
            });
}
