package chisel.core;

public enum VariantModelType {
    CUBE_ALL,
    PILLAR,
    BOOKSHELF,
    TOP_BOTTOM_SIDE,
    TOP_BOTTOM_SIDE_CONNECTED_VERTICALLY,
    CONNECTED,
    CONNECTED_VERTICALLY,
    CONNECTED_HORIZONTALLY,
    MULTI_LAYER
}
