package io.github.chiselteam.chisel.content.compat;

import io.github.chiselteam.chisel.api.model.ChiselModelHandlers;
import io.github.chiselteam.chisel.content.ChiselFamily;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.List;

public class AppliedEnergisticsFamilies {
    public static final ChiselFamily AE2_CERTUS = ChiselFamily.build("ae2_certus", builder -> builder
            .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE))
            .addVariant("certus_array", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_array", "Certus Quartz", "Array")
            .addVariant("certus_border_square", ChiselModelHandlers.CONNECTED).translation("certus_border_square", "Certus Quartz", "Square Border")
            .addVariant("certus_braid").translation("certus_braid", "Certus Quartz", "Braid")
            .addVariant("certus_braid_encased", ChiselModelHandlers.CONNECTED).translation("certus_braid_encased", "Certus Quartz", "Encased Braid")
            .addVariant("certus_bricks_cracked").translation("certus_bricks_cracked", "Certus Quartz", "Cracked Bricks")
            .addVariant("certus_bricks_encased", ChiselModelHandlers.CONNECTED).translation("certus_bricks_encased", "Certus Quartz", "Encased Bricks")
            .addVariant("certus_bricks_indent").translation("certus_bricks_indent", "Certus Quartz", "Indent Bricks")
            .addVariant("certus_bricks_inlayed").translation("certus_bricks_inlayed", "Certus Quartz", "Inlayed Bricks")
            .addVariant("certus_bricks_large", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_bricks_large", "Certus Quartz", "Large Bricks")
            .addVariant("certus_bricks_small").translation("certus_bricks_small", "Certus Quartz", "Small Bricks")
            .addVariant("certus_bricks_soft").translation("certus_bricks_soft", "Certus Quartz", "Soft Bricks")
            .addVariant("certus_bricks_solid").translation("certus_bricks_solid", "Certus Quartz", "Solid Bricks")
            .addVariant("certus_bricks_triple").translation("certus_bricks_triple", "Certus Quartz", "Triple Bricks")
            .addVariant("certus_bricks_vertical").translation("certus_bricks_vertical", "Certus Quartz", "Vertical Bricks")
            .addVariant("certus_chaotic", ChiselModelHandlers.MULTIBLOCK_3X3).translation("certus_chaotic", "Certus Quartz", "Chaotic")
            .addVariant("certus_chaotic_medium").translation("certus_chaotic_medium", "Certus Quartz", "Chaotic Medium")
            .addVariant("certus_chaotic_small").translation("certus_chaotic_small", "Certus Quartz", "Chaotic Small")
            .addVariant("certus_checker").translation("certus_checker", "Certus Quartz", "Checker")
            .addVariant("certus_checker_small").translation("certus_checker_small", "Certus Quartz", "Small Checker")
            .addVariant("certus_circular", ChiselModelHandlers.CONNECTED).translation("certus_circular", "Certus Quartz", "Circular")
            .addVariant("certus_cobble").translation("certus_cobble", "Certus Quartz", "Cobble")
            .addVariant("certus_cuts", ChiselModelHandlers.MULTIBLOCK_4X4).translation("certus_cuts", "Certus Quartz", "Cuts")
            .addVariant("certus_dent", ChiselModelHandlers.CONNECTED).translation("certus_dent", "Certus Quartz", "Dent")
            .addVariant("certus_french_1").translation("certus_french_1", "Certus Quartz", "French 1")
            .addVariant("certus_french_2").translation("certus_french_2", "Certus Quartz", "French 2")
            .addVariant("certus_indent", ChiselModelHandlers.CONNECTED).translation("certus_indent", "Certus Quartz", "Indent")
            .addVariant("certus_jellybean", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_jellybean", "Certus Quartz", "Jellybean")
            .addVariant("certus_layers").translation("certus_layers", "Certus Quartz", "Layers")
            .addVariant("certus_layers_connected", ChiselModelHandlers.CONNECTED).translation("certus_layers_connected", "Certus Quartz", "Layers Connected")
            .addVariant("certus_line_horizontal").translation("certus_line_horizontal", "Certus Quartz", "Horizontal Line")
            .addVariant("certus_line_vertical").translation("certus_line_vertical", "Certus Quartz", "Vertical Line")
            .addVariant("certus_meander_horizontal", ChiselModelHandlers.CTMH).translation("certus_meander_horizontal", "Certus Quartz", "Horizontal Meander")
            .addVariant("certus_meander_vertical", ChiselModelHandlers.CTMV).translation("certus_meander_vertical", "Certus Quartz", "Vertical Meander")
            .addVariant("certus_mosaic", ChiselModelHandlers.CONNECTED).translation("certus_mosaic", "Certus Quartz", "Mosaic")
            .addVariant("certus_ornate_small").translation("certus_ornate_small", "Certus Quartz", "Small Ornate")
            .addVariant("certus_panel").translation("certus_panel", "Certus Quartz", "Panel")
            .addVariant("certus_pillar", ChiselModelHandlers.TBS).translation("certus_pillar", "Certus Quartz", "Pillar")
            .addVariant("certus_pillar_basic", ChiselModelHandlers.CTMV).translation("certus_pillar_basic", "Certus Quartz", "Basic Pillar")
            .addVariant("certus_pillar_basic_dent", ChiselModelHandlers.CTMV).translation("certus_pillar_basic_dent", "Certus Quartz", "Basic Dent Pillar")
            .addVariant("certus_pillar_basic_plain", ChiselModelHandlers.CTMV).translation("certus_pillar_basic_plain", "Certus Quartz", "Basic Plain Pillar")
            .addVariant("certus_pillar_basic_round", ChiselModelHandlers.CTMV).translation("certus_pillar_basic_round", "Certus Quartz", "Basic Round Pillar")
            .addVariant("certus_pillar_basic_spiral", ChiselModelHandlers.CTMV).translation("certus_pillar_basic_spiral", "Certus Quartz", "Basic Spiral Pillar")
            .addVariant("certus_pillar_classic", ChiselModelHandlers.TBS).translation("certus_pillar_classic", "Certus Quartz", "Classic Pillar")
            .addVariant("certus_pillar_classic_large", ChiselModelHandlers.TBS).translation("certus_pillar_classic_large", "Certus Quartz", "Large Classic Pillar")
            .addVariant("certus_pillar_ionic", ChiselModelHandlers.CTMV).translation("certus_pillar_ionic", "Certus Quartz", "Ionic Pillar")
            .addVariant("certus_pillar_ionic_dent", ChiselModelHandlers.CTMV).translation("certus_pillar_ionic_dent", "Certus Quartz", "Ionic Dent Pillar")
            .addVariant("certus_pillar_ionic_plain", ChiselModelHandlers.CTMV).translation("certus_pillar_ionic_plain", "Certus Quartz", "Ionic Plain Pillar")
            .addVariant("certus_pillar_ionic_round", ChiselModelHandlers.CTMV).translation("certus_pillar_ionic_round", "Certus Quartz", "Ionic Round Pillar")
            .addVariant("certus_pillar_ionic_spiral", ChiselModelHandlers.CTMV).translation("certus_pillar_ionic_spiral", "Certus Quartz", "Ionic Spiral Pillar")
            .addVariant("certus_pillar_large_basic_triple", ChiselModelHandlers.CTMV).translation("certus_pillar_large_basic_triple", "Certus Quartz", "Large Basic Triple Pillar")
            .addVariant("certus_pillar_large_ionic_triple", ChiselModelHandlers.CTMV).translation("certus_pillar_large_ionic_triple", "Certus Quartz", "Large Ionic Triple Pillar")
            .addVariant("certus_pillar_meander", ChiselModelHandlers.CTMV).translation("certus_pillar_meander", "Certus Quartz", "Meander Pillar")
            .addVariant("certus_pillar_meander_dent", ChiselModelHandlers.CTMV).translation("certus_pillar_meander_dent", "Certus Quartz", "Meander Dent Pillar")
            .addVariant("certus_pillar_meander_plain", ChiselModelHandlers.CTMV).translation("certus_pillar_meander_plain", "Certus Quartz", "Meander Plain Pillar")
            .addVariant("certus_pillar_meander_round", ChiselModelHandlers.CTMV).translation("certus_pillar_meander_round", "Certus Quartz", "Meander Round Pillar")
            .addVariant("certus_pillar_meander_spiral", ChiselModelHandlers.CTMV).translation("certus_pillar_meander_spiral", "Certus Quartz", "Meander Spiral Pillar")
            .addVariant("certus_plate").translation("certus_plate", "Certus Quartz", "Plate")
            .addVariant("certus_plate_connected", ChiselModelHandlers.CONNECTED).translation("certus_plate_connected", "Certus Quartz", "Plate Connected")
            .addVariant("certus_polished").translation("certus_polished", "Certus Quartz", "Polished")
            .addVariant("certus_polished_encased", ChiselModelHandlers.CONNECTED).translation("certus_polished_encased", "Certus Quartz", "Polished Encased")
            .addVariant("certus_prism").translation("certus_prism", "Certus Quartz", "Prismatic")
            .addVariant("certus_raw").translation("certus_raw", "Certus Quartz", "Raw")
            .addVariant("certus_road").translation("certus_road", "Certus Quartz", "Road")
            .addVariant("certus_slanted", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_slanted", "Certus Quartz", "Slanted")
            .addVariant("certus_tiles").translation("certus_tiles", "Certus Quartz", "Tiles")
            .addVariant("certus_tiles_large", ChiselModelHandlers.CONNECTED).translation("certus_tiles_large", "Certus Quartz", "Large Tiles")
            .addVariant("certus_tiles_small").translation("certus_tiles_small", "Certus Quartz", "Small Tiles")
            .addVariant("certus_twisted", ChiselModelHandlers.TBS).translation("certus_twisted", "Certus Quartz", "Twisted")
            .addVariant("certus_weaver", ChiselModelHandlers.CONNECTED).translation("certus_weaver", "Certus Quartz", "Weaver")
            .addVariant("certus_zag", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_zag", "Certus Quartz", "Zag")
            .addVariant("certus_crate", ChiselModelHandlers.CONNECTED).translation("certus_crate", "Certus Quartz", "Crate")
            .addVariant("certus_herringbone").translation("certus_herringbone", "Certus Quartz", "Herringbone")
            .addVariant("certus_herringbone_encased", ChiselModelHandlers.CONNECTED).translation("certus_herringbone_encased", "Certus Quartz", "Encased Herringbone")
            .addVariant("certus_medallion").translation("certus_medallion", "Certus Quartz", "Medallion")
            .addVariant("certus_medallion_encased", ChiselModelHandlers.CONNECTED).translation("certus_medallion_encased", "Certus Quartz", "Encased Medallion")
            .addVariant("certus_dots").translation("certus_dots", "Certus Quartz", "Dots")
            .addVariant("certus_dots_encased", ChiselModelHandlers.CONNECTED).translation("certus_dots_encased", "Certus Quartz", "Encased Dots")
            .addVariant("certus_heart").translation("certus_heart", "Certus Quartz", "Heart")
            .addVariant("certus_star").translation("certus_star", "Certus Quartz", "Star")
            .addVariant("certus_plating").translation("certus_plating", "Certus Quartz", "Plating")
            .addVariant("certus_lodestone").translation("certus_lodestone", "Certus Quartz", "Lodestone")
            .addVariant("certus_lodestone_connected", ChiselModelHandlers.CONNECTED).translation("certus_lodestone_connected", "Certus Quartz", "Lodestone Connected")
            .addVariant("certus_plank").translation("certus_plank", "Certus Quartz", "Plank")
            .addVariant("certus_plank_connected", ChiselModelHandlers.CONNECTED).translation("certus_plank_connected", "Certus Quartz", "Plank Connected")
            .addVariant("certus_frame").translation("certus_frame", "Certus Quartz", "Frame")
            .addVariant("certus_panel_1").translation("certus_panel_1", "Certus Quartz", "Panel 1")
            .addVariant("certus_panel_2").translation("certus_panel_2", "Certus Quartz", "Panel 2")
            .addVariant("certus_panel_3").translation("certus_panel_3", "Certus Quartz", "Panel 3")
            .addVariant("certus_skull_creeper").translation("certus_skull_creeper", "Certus Quartz", "Creeper Skull")
            .addVariant("certus_skull_skeleton").translation("certus_skull_skeleton", "Certus Quartz", "Skeleton Skull")
            .addVariant("certus_stripes").translation("certus_stripes", "Certus Quartz", "Stripes")
            .addVariant("certus_stripes_encased", ChiselModelHandlers.CONNECTED).translation("certus_stripes_encased", "Certus Quartz", "Encased Stripes")
            .addVariant("certus_chisel_1").translation("certus_chisel_1", "Certus Quartz", "Chisel 1")
            .addVariant("certus_chisel_2").translation("certus_chisel_2", "Certus Quartz", "Chisel 2")
            .addVariant("certus_chisel_3").translation("certus_chisel_3", "Certus Quartz", "Chisel 3")
            .addVariant("certus_chisel_4").translation("certus_chisel_4", "Certus Quartz", "Chisel 4")
            .addVariant("certus_chisel_5").translation("certus_chisel_5", "Certus Quartz", "Chisel 5")
            .addVariant("certus_chisel_6").translation("certus_chisel_6", "Certus Quartz", "Chisel 6")
            .addVariant("certus_facet").translation("certus_facet", "Certus Quartz", "Facet")
            .addVariant("certus_facet_small").translation("certus_facet_small", "Certus Quartz", "Small Facet")
            .addVariant("certus_facet_small_encased", ChiselModelHandlers.CONNECTED).translation("certus_facet_small_encased", "Certus Quartz", "Encased Small Facet")
            .addVariant("certus_shiny").translation("certus_shiny", "Certus Quartz", "Shiny")
            .addVariant("certus_shiny_connected", ChiselModelHandlers.CONNECTED).translation("certus_shiny_connected", "Certus Quartz", "Shiny Connected")
            .addVariant("certus_gem").translation("certus_gem", "Certus Quartz", "Gem")
            .addVariant("certus_gem_1").translation("certus_gem_1", "Certus Quartz", "Gem 1")
            .addVariant("certus_gem_1_connected", ChiselModelHandlers.CONNECTED).translation("certus_gem_1_connected", "Certus Quartz", "Gem 1 Connected")
            .addVariant("certus_gem_2").translation("certus_gem_2", "Certus Quartz", "Gem 2")
            .addVariant("certus_gem_2_connected", ChiselModelHandlers.CONNECTED).translation("certus_gem_2_connected", "Certus Quartz", "Gem 2 Connected")
            .addVariant("certus_gem_3").translation("certus_gem_3", "Certus Quartz", "Gem 3")
            .addVariant("certus_gem_3_connected", ChiselModelHandlers.CONNECTED).translation("certus_gem_3_connected", "Certus Quartz", "Gem 3 Connected")
            .addVariant("certus_bricks_square").translation("certus_bricks_square", "Certus Quartz", "Square Bricks")
            .addVariant("certus_slab").translation("certus_slab", "Certus Quartz", "Slab")
            .addVariant("certus_scaffold").translation("certus_scaffold", "Certus Quartz", "Scaffold")
            .addVariant("certus_scaffold_encased", ChiselModelHandlers.CONNECTED).translation("certus_scaffold_encased", "Certus Quartz", "Encased Scaffold")
            .addVariant("certus_tiles_inlayed").translation("certus_tiles_inlayed", "Certus Quartz", "Inlayed Tiles")
            .addVariant("certus_waves", ChiselModelHandlers.MULTIBLOCK_2X2).translation("certus_waves", "Certus Quartz", "Waves")
            .addVariant("certus_parquet").translation("certus_parquet", "Certus Quartz", "Parquet")
            .addVariant("certus_parquet_encased", ChiselModelHandlers.CONNECTED).translation("certus_parquet_encased", "Certus Quartz", "Encased Parquet")
            .build());

    public static final ChiselFamily AE2_SKY_STONE = ChiselFamily.build("ae2_sky_stone", builder -> builder
            .properties(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE))
            .addVariant("sky_stone_array", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_array", "Sky Stone", "Array")
            .addVariant("sky_stone_border_square", ChiselModelHandlers.CONNECTED).translation("sky_stone_border_square", "Sky Stone", "Square Border")
            .addVariant("sky_stone_braid").translation("sky_stone_braid", "Sky Stone", "Braid")
            .addVariant("sky_stone_braid_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_braid_encased", "Sky Stone", "Encased Braid")
            .addVariant("sky_stone_bricks_cracked").translation("sky_stone_bricks_cracked", "Sky Stone", "Cracked Bricks")
            .addVariant("sky_stone_bricks_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_bricks_encased", "Sky Stone", "Encased Bricks")
            .addVariant("sky_stone_bricks_indent").translation("sky_stone_bricks_indent", "Sky Stone", "Indent Bricks")
            .addVariant("sky_stone_bricks_inlayed").translation("sky_stone_bricks_inlayed", "Sky Stone", "Inlayed Bricks")
            .addVariant("sky_stone_bricks_large", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_bricks_large", "Sky Stone", "Large Bricks")
            .addVariant("sky_stone_bricks_small").translation("sky_stone_bricks_small", "Sky Stone", "Small Bricks")
            .addVariant("sky_stone_bricks_soft").translation("sky_stone_bricks_soft", "Sky Stone", "Soft Bricks")
            .addVariant("sky_stone_bricks_solid").translation("sky_stone_bricks_solid", "Sky Stone", "Solid Bricks")
            .addVariant("sky_stone_bricks_triple").translation("sky_stone_bricks_triple", "Sky Stone", "Triple Bricks")
            .addVariant("sky_stone_bricks_vertical").translation("sky_stone_bricks_vertical", "Sky Stone", "Vertical Bricks")
            .addVariant("sky_stone_chaotic", ChiselModelHandlers.MULTIBLOCK_3X3).translation("sky_stone_chaotic", "Sky Stone", "Chaotic")
            .addVariant("sky_stone_chaotic_medium").translation("sky_stone_chaotic_medium", "Sky Stone", "Chaotic Medium")
            .addVariant("sky_stone_chaotic_small").translation("sky_stone_chaotic_small", "Sky Stone", "Chaotic Small")
            .addVariant("sky_stone_checker").translation("sky_stone_checker", "Sky Stone", "Checker")
            .addVariant("sky_stone_checker_small").translation("sky_stone_checker_small", "Sky Stone", "Small Checker")
            .addVariant("sky_stone_circular", ChiselModelHandlers.CONNECTED).translation("sky_stone_circular", "Sky Stone", "Circular")
            .addVariant("sky_stone_cobble").translation("sky_stone_cobble", "Sky Stone", "Cobble")
            .addVariant("sky_stone_cuts", ChiselModelHandlers.MULTIBLOCK_4X4).translation("sky_stone_cuts", "Sky Stone", "Cuts")
            .addVariant("sky_stone_dent", ChiselModelHandlers.CONNECTED).translation("sky_stone_dent", "Sky Stone", "Dent")
            .addVariant("sky_stone_french_1").translation("sky_stone_french_1", "Sky Stone", "French 1")
            .addVariant("sky_stone_french_2").translation("sky_stone_french_2", "Sky Stone", "French 2")
            .addVariant("sky_stone_indent", ChiselModelHandlers.CONNECTED).translation("sky_stone_indent", "Sky Stone", "Indent")
            .addVariant("sky_stone_jellybean", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_jellybean", "Sky Stone", "Jellybean")
            .addVariant("sky_stone_layers").translation("sky_stone_layers", "Sky Stone", "Layers")
            .addVariant("sky_stone_layers_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_layers_connected", "Sky Stone", "Layers Connected")
            .addVariant("sky_stone_line_horizontal").translation("sky_stone_line_horizontal", "Sky Stone", "Horizontal Line")
            .addVariant("sky_stone_line_vertical").translation("sky_stone_line_vertical", "Sky Stone", "Vertical Line")
            .addVariant("sky_stone_meander_horizontal", ChiselModelHandlers.CTMH).translation("sky_stone_meander_horizontal", "Sky Stone", "Horizontal Meander")
            .addVariant("sky_stone_meander_vertical", ChiselModelHandlers.CTMV).translation("sky_stone_meander_vertical", "Sky Stone", "Vertical Meander")
            .addVariant("sky_stone_mosaic", ChiselModelHandlers.CONNECTED).translation("sky_stone_mosaic", "Sky Stone", "Mosaic")
            .addVariant("sky_stone_ornate_small").translation("sky_stone_ornate_small", "Sky Stone", "Small Ornate")
            .addVariant("sky_stone_panel").translation("sky_stone_panel", "Sky Stone", "Panel")
            .addVariant("sky_stone_pillar", ChiselModelHandlers.TBS).translation("sky_stone_pillar", "Sky Stone", "Pillar")
            .addVariant("sky_stone_pillar_basic", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_basic", "Sky Stone", "Basic Pillar")
            .addVariant("sky_stone_pillar_basic_dent", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_basic_dent", "Sky Stone", "Basic Dent Pillar")
            .addVariant("sky_stone_pillar_basic_plain", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_basic_plain", "Sky Stone", "Basic Plain Pillar")
            .addVariant("sky_stone_pillar_basic_round", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_basic_round", "Sky Stone", "Basic Round Pillar")
            .addVariant("sky_stone_pillar_basic_spiral", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_basic_spiral", "Sky Stone", "Basic Spiral Pillar")
            .addVariant("sky_stone_pillar_classic", ChiselModelHandlers.TBS).translation("sky_stone_pillar_classic", "Sky Stone", "Classic Pillar")
            .addVariant("sky_stone_pillar_classic_large", ChiselModelHandlers.TBS).translation("sky_stone_pillar_classic_large", "Sky Stone", "Large Classic Pillar")
            .addVariant("sky_stone_pillar_ionic", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_ionic", "Sky Stone", "Ionic Pillar")
            .addVariant("sky_stone_pillar_ionic_dent", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_ionic_dent", "Sky Stone", "Ionic Dent Pillar")
            .addVariant("sky_stone_pillar_ionic_plain", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_ionic_plain", "Sky Stone", "Ionic Plain Pillar")
            .addVariant("sky_stone_pillar_ionic_round", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_ionic_round", "Sky Stone", "Ionic Round Pillar")
            .addVariant("sky_stone_pillar_ionic_spiral", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_ionic_spiral", "Sky Stone", "Ionic Spiral Pillar")
            .addVariant("sky_stone_pillar_large_basic_triple", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_large_basic_triple", "Sky Stone", "Large Basic Triple Pillar")
            .addVariant("sky_stone_pillar_large_ionic_triple", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_large_ionic_triple", "Sky Stone", "Large Ionic Triple Pillar")
            .addVariant("sky_stone_pillar_meander", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_meander", "Sky Stone", "Meander Pillar")
            .addVariant("sky_stone_pillar_meander_dent", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_meander_dent", "Sky Stone", "Meander Dent Pillar")
            .addVariant("sky_stone_pillar_meander_plain", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_meander_plain", "Sky Stone", "Meander Plain Pillar")
            .addVariant("sky_stone_pillar_meander_round", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_meander_round", "Sky Stone", "Meander Round Pillar")
            .addVariant("sky_stone_pillar_meander_spiral", ChiselModelHandlers.CTMV).translation("sky_stone_pillar_meander_spiral", "Sky Stone", "Meander Spiral Pillar")
            .addVariant("sky_stone_plate").translation("sky_stone_plate", "Sky Stone", "Plate")
            .addVariant("sky_stone_plate_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_plate_connected", "Sky Stone", "Plate Connected")
            .addVariant("sky_stone_polished").translation("sky_stone_polished", "Sky Stone", "Polished")
            .addVariant("sky_stone_polished_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_polished_encased", "Sky Stone", "Polished Encased")
            .addVariant("sky_stone_prism").translation("sky_stone_prism", "Sky Stone", "Prismatic")
            .addVariant("sky_stone_raw").translation("sky_stone_raw", "Sky Stone", "Raw")
            .addVariant("sky_stone_road").translation("sky_stone_road", "Sky Stone", "Road")
            .addVariant("sky_stone_slanted", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_slanted", "Sky Stone", "Slanted")
            .addVariant("sky_stone_tiles").translation("sky_stone_tiles", "Sky Stone", "Tiles")
            .addVariant("sky_stone_tiles_large", ChiselModelHandlers.CONNECTED).translation("sky_stone_tiles_large", "Sky Stone", "Large Tiles")
            .addVariant("sky_stone_tiles_small").translation("sky_stone_tiles_small", "Sky Stone", "Small Tiles")
            .addVariant("sky_stone_twisted", ChiselModelHandlers.TBS).translation("sky_stone_twisted", "Sky Stone", "Twisted")
            .addVariant("sky_stone_weaver", ChiselModelHandlers.CONNECTED).translation("sky_stone_weaver", "Sky Stone", "Weaver")
            .addVariant("sky_stone_zag", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_zag", "Sky Stone", "Zag")
            .addVariant("sky_stone_crate", ChiselModelHandlers.CONNECTED).translation("sky_stone_crate", "Sky Stone", "Crate")
            .addVariant("sky_stone_herringbone").translation("sky_stone_herringbone", "Sky Stone", "Herringbone")
            .addVariant("sky_stone_herringbone_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_herringbone_encased", "Sky Stone", "Encased Herringbone")
            .addVariant("sky_stone_medallion").translation("sky_stone_medallion", "Sky Stone", "Medallion")
            .addVariant("sky_stone_medallion_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_medallion_encased", "Sky Stone", "Encased Medallion")
            .addVariant("sky_stone_dots").translation("sky_stone_dots", "Sky Stone", "Dots")
            .addVariant("sky_stone_dots_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_dots_encased", "Sky Stone", "Encased Dots")
            .addVariant("sky_stone_heart").translation("sky_stone_heart", "Sky Stone", "Heart")
            .addVariant("sky_stone_star").translation("sky_stone_star", "Sky Stone", "Star")
            .addVariant("sky_stone_plating").translation("sky_stone_plating", "Sky Stone", "Plating")
            .addVariant("sky_stone_lodestone").translation("sky_stone_lodestone", "Sky Stone", "Lodestone")
            .addVariant("sky_stone_lodestone_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_lodestone_connected", "Sky Stone", "Lodestone Connected")
            .addVariant("sky_stone_plank").translation("sky_stone_plank", "Sky Stone", "Plank")
            .addVariant("sky_stone_plank_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_plank_connected", "Sky Stone", "Plank Connected")
            .addVariant("sky_stone_frame").translation("sky_stone_frame", "Sky Stone", "Frame")
            .addVariant("sky_stone_panel_1").translation("sky_stone_panel_1", "Sky Stone", "Panel 1")
            .addVariant("sky_stone_panel_2").translation("sky_stone_panel_2", "Sky Stone", "Panel 2")
            .addVariant("sky_stone_panel_3").translation("sky_stone_panel_3", "Sky Stone", "Panel 3")
            .addVariant("sky_stone_skull_creeper").translation("sky_stone_skull_creeper", "Sky Stone", "Creeper Skull")
            .addVariant("sky_stone_skull_skeleton").translation("sky_stone_skull_skeleton", "Sky Stone", "Skeleton Skull")
            .addVariant("sky_stone_stripes").translation("sky_stone_stripes", "Sky Stone", "Stripes")
            .addVariant("sky_stone_stripes_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_stripes_encased", "Sky Stone", "Encased Stripes")
            .addVariant("sky_stone_chisel_1").translation("sky_stone_chisel_1", "Sky Stone", "Chisel 1")
            .addVariant("sky_stone_chisel_2").translation("sky_stone_chisel_2", "Sky Stone", "Chisel 2")
            .addVariant("sky_stone_chisel_3").translation("sky_stone_chisel_3", "Sky Stone", "Chisel 3")
            .addVariant("sky_stone_chisel_4").translation("sky_stone_chisel_4", "Sky Stone", "Chisel 4")
            .addVariant("sky_stone_chisel_5").translation("sky_stone_chisel_5", "Sky Stone", "Chisel 5")
            .addVariant("sky_stone_chisel_6").translation("sky_stone_chisel_6", "Sky Stone", "Chisel 6")
            .addVariant("sky_stone_facet").translation("sky_stone_facet", "Sky Stone", "Facet")
            .addVariant("sky_stone_facet_small").translation("sky_stone_facet_small", "Sky Stone", "Small Facet")
            .addVariant("sky_stone_facet_small_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_facet_small_encased", "Sky Stone", "Encased Small Facet")
            .addVariant("sky_stone_shiny").translation("sky_stone_shiny", "Sky Stone", "Shiny")
            .addVariant("sky_stone_shiny_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_shiny_connected", "Sky Stone", "Shiny Connected")
            .addVariant("sky_stone_gem").translation("sky_stone_gem", "Sky Stone", "Gem")
            .addVariant("sky_stone_gem_1").translation("sky_stone_gem_1", "Sky Stone", "Gem 1")
            .addVariant("sky_stone_gem_1_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_gem_1_connected", "Sky Stone", "Gem 1 Connected")
            .addVariant("sky_stone_gem_2").translation("sky_stone_gem_2", "Sky Stone", "Gem 2")
            .addVariant("sky_stone_gem_2_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_gem_2_connected", "Sky Stone", "Gem 2 Connected")
            .addVariant("sky_stone_gem_3").translation("sky_stone_gem_3", "Sky Stone", "Gem 3")
            .addVariant("sky_stone_gem_3_connected", ChiselModelHandlers.CONNECTED).translation("sky_stone_gem_3_connected", "Sky Stone", "Gem 3 Connected")
            .addVariant("sky_stone_bricks_square").translation("sky_stone_bricks_square", "Sky Stone", "Square Bricks")
            .addVariant("sky_stone_slab").translation("sky_stone_slab", "Sky Stone", "Slab")
            .addVariant("sky_stone_scaffold").translation("sky_stone_scaffold", "Sky Stone", "Scaffold")
            .addVariant("sky_stone_scaffold_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_scaffold_encased", "Sky Stone", "Encased Scaffold")
            .addVariant("sky_stone_tiles_inlayed").translation("sky_stone_tiles_inlayed", "Sky Stone", "Inlayed Tiles")
            .addVariant("sky_stone_waves", ChiselModelHandlers.MULTIBLOCK_2X2).translation("sky_stone_waves", "Sky Stone", "Waves")
            .addVariant("sky_stone_parquet").translation("sky_stone_parquet", "Sky Stone", "Parquet")
            .addVariant("sky_stone_parquet_encased", ChiselModelHandlers.CONNECTED).translation("sky_stone_parquet_encased", "Sky Stone", "Encased Parquet")
            .build());

    private static final List<ChiselFamily> FAMILIES = List.of(AE2_CERTUS, AE2_SKY_STONE);

    private AppliedEnergisticsFamilies() {
    }

    public static List<ChiselFamily> families() {
        return FAMILIES;
    }
}
