package io.github.chiselteam.chisel.api.model;

import io.github.chiselteam.chisel.api.model.impl.*;

public class ChiselModelHandlers {
    public static final VariantModelHandler CUBE_ALL = new CubeAllVariantModelHandler("cube_all");
    public static final VariantModelHandler SHADELESS = new CubeAllVariantModelHandler("shadeless");
    public static final VariantModelHandler SHADELESS_MULTI_LAYER = new CubeAllVariantModelHandler("shadeless_multi_layer");
    public static final VariantModelHandler PILLAR = new CubeAllVariantModelHandler("pillar");
    public static final VariantModelHandler BOOKSHELF = new DirectionalCTMVariantModelHandler("bookshelf", true);
    public static final VariantModelHandler TBS = new CubeAllVariantModelHandler("top_bottom_side");
    public static final VariantModelHandler CONNECTED = new CTMVariantModelHandler("connected");
    public static final VariantModelHandler CONNECTED_NO_AO = new CTMVariantModelHandler("connected_no_ao");
    public static final VariantModelHandler CONNECTED_TBS = new TBSCTMVariantModelHandler("connected_tbs");
    public static final VariantModelHandler CTMV = new DirectionalCTMVariantModelHandler("ctmv", false);
    public static final VariantModelHandler CTMH = new DirectionalCTMVariantModelHandler("ctmh", false);
    public static final VariantModelHandler MULTI_LAYER = new CubeAllVariantModelHandler("multi_layer");
    public static final VariantModelHandler MULTI_LAYER_TBS = new CubeAllVariantModelHandler("multi_layer_tbs");
    public static final VariantModelHandler MULTI_LAYER_TBS_TINTED = new CubeAllVariantModelHandler("multi_layer_tbs_tinted");
    public static final VariantModelHandler MULTI_LAYER_LAVA = new CubeAllVariantModelHandler("multi_layer_lava");
    public static final VariantModelHandler MULTI_LAYER_LAVA_TOP_BOTTOM_SIDE = new CubeAllVariantModelHandler("multi_layer_lava_top_bottom_side");
    public static final VariantModelHandler LAVA_2x2 = new MultiblockCTMVariantModelHandler("lava_2x2", false, 2, true);
    public static final VariantModelHandler LAVA_3x3 = new MultiblockCTMVariantModelHandler("lava_3x3", false, 3, true);
    public static final VariantModelHandler LAVA_4x4 = new MultiblockCTMVariantModelHandler("lava_4x4", false, 4, true);
    public static final VariantModelHandler MULTI_LAYER_WATER = new CubeAllVariantModelHandler("multi_layer_water");
    public static final VariantModelHandler MULTI_LAYER_CONNECTED = new CTMVariantModelHandler("multi_layer_connected", true);
    public static final VariantModelHandler MULTI_LAYER_CONNECTED_TINTED = new CTMVariantModelHandler("multi_layer_connected_tinted", true);
    public static final VariantModelHandler MULTI_LAYER_CONNECTED_GLOW = new CTMVariantModelHandler("multi_layer_connected_glow");
    public static final VariantModelHandler ANTIBLOCK = new CTMVariantModelHandler("antiblock");
    public static final VariantModelHandler LAYERED_MULTI_LAYER_CONNECTED_GLOW = new CTMVariantModelHandler("layered_multi_layer_connected_glow");
    public static final VariantModelHandler CARPET = new CubeAllVariantModelHandler("carpet");
    public static final VariantModelHandler IRON_BARS = new CubeAllVariantModelHandler("iron_bars");
    public static final VariantModelHandler GLASS_PANE = new CubeAllVariantModelHandler("glass_pane");
    public static final VariantModelHandler MOSSY = new CubeAllVariantModelHandler("mossy");
    public static final VariantModelHandler MOSSY_TOP_BOTTOM_SIDE = new CubeAllVariantModelHandler("mossy_top_bottom_side");
    public static final VariantModelHandler PUMPKIN = new CubeAllVariantModelHandler("pumpkin");
    public static final VariantModelHandler TORCH = new CubeAllVariantModelHandler("torch");
    public static final VariantModelHandler WALL_TORCH = new WallTorchVariantModelHandler("wall_torch");
    public static final VariantModelHandler ROAD_LINES = new CubeAllVariantModelHandler("road_lines");
    public static final VariantModelHandler V4 = new MultiblockCTMVariantModelHandler("v4", false, 2, false);
    public static final VariantModelHandler V9 = new MultiblockCTMVariantModelHandler("v9", false, 3, false);
    public static final VariantModelHandler V16 = new MultiblockCTMVariantModelHandler("v16", false, 4, false);
    public static final VariantModelHandler R4 = new MultiblockCTMVariantModelHandler("r4", true, 2, false);
    public static final VariantModelHandler R9 = new MultiblockCTMVariantModelHandler("r9", true, 3, false);
    public static final VariantModelHandler R16 = new MultiblockCTMVariantModelHandler("r16", true, 4, false);
    public static final VariantModelHandler AR = new ARVariantModelHandler("ar");
    public static final VariantModelHandler MULTI_LAYER_LAVA_AR = new ARVariantModelHandler("multi_layer_lava_ar", true);
    public static final VariantModelHandler MULTI_LAYER_WATER_AR = new ARVariantModelHandler("multi_layer_water_ar", true);
    public static final VariantModelHandler MULTIBLOCK_2X2 = new MultiblockCTMVariantModelHandler("multiblock_2x2", false, 2, false);
    public static final VariantModelHandler MULTIBLOCK_3X3 = new MultiblockCTMVariantModelHandler("multiblock_3x3", false, 3, false);
    public static final VariantModelHandler MULTIBLOCK_4X4 = new MultiblockCTMVariantModelHandler("multiblock_4x4", false, 4, false);
    public static final VariantModelHandler MULTI_LAYER_WATER_2X2 = new MultiblockCTMVariantModelHandler("multi_layer_water_2x2", false, 2, true);
    public static final VariantModelHandler MULTI_LAYER_WATER_3X3 = new MultiblockCTMVariantModelHandler("multi_layer_water_3x3", false, 3, true);
    public static final VariantModelHandler MULTI_LAYER_WATER_4X4 = new MultiblockCTMVariantModelHandler("multi_layer_water_4x4", false, 4, true);
    public static final VariantModelHandler REDSTONE_LAMP = new CubeAllVariantModelHandler("redstone_lamp");
    public static final VariantModelHandler GLASS = new CTMVariantModelHandler("glass");
    public static final VariantModelHandler ICE = new CTMVariantModelHandler("ice");
    public static final VariantModelHandler ICE_2X2 = new MultiblockCTMVariantModelHandler("ice_2x2", false, 2, false);
    public static final VariantModelHandler ICE_3X3 = new MultiblockCTMVariantModelHandler("ice_3x3", false, 3, false);
    public static final VariantModelHandler ICE_4X4 = new MultiblockCTMVariantModelHandler("ice_4x4", false, 4, false);
    public static final VariantModelHandler ICE_AR = new ARVariantModelHandler("ice_ar");

    public static void registerAll() {
        VariantModelHandlers.register(CUBE_ALL);
        VariantModelHandlers.register(SHADELESS);
        VariantModelHandlers.register(SHADELESS_MULTI_LAYER);
        VariantModelHandlers.register(PILLAR);
        VariantModelHandlers.register(BOOKSHELF);
        VariantModelHandlers.register(TBS);
        VariantModelHandlers.register(CONNECTED);
        VariantModelHandlers.register(CONNECTED_NO_AO);
        VariantModelHandlers.register(CONNECTED_TBS);
        VariantModelHandlers.register(CTMV);
        VariantModelHandlers.register(CTMH);
        VariantModelHandlers.register(MULTI_LAYER);
        VariantModelHandlers.register(MULTI_LAYER_TBS);
        VariantModelHandlers.register(MULTI_LAYER_TBS_TINTED);
        VariantModelHandlers.register(MULTI_LAYER_LAVA);
        VariantModelHandlers.register(MULTI_LAYER_LAVA_TOP_BOTTOM_SIDE);
        VariantModelHandlers.register(LAVA_2x2);
        VariantModelHandlers.register(LAVA_3x3);
        VariantModelHandlers.register(LAVA_4x4);
        VariantModelHandlers.register(MULTI_LAYER_WATER);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED_TINTED);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED_GLOW);
        VariantModelHandlers.register(LAYERED_MULTI_LAYER_CONNECTED_GLOW);
        VariantModelHandlers.register(CARPET);
        VariantModelHandlers.register(IRON_BARS);
        VariantModelHandlers.register(GLASS_PANE);
        VariantModelHandlers.register(MOSSY);
        VariantModelHandlers.register(MOSSY_TOP_BOTTOM_SIDE);
        VariantModelHandlers.register(PUMPKIN);
        VariantModelHandlers.register(TORCH);
        VariantModelHandlers.register(WALL_TORCH);
        VariantModelHandlers.register(ROAD_LINES);
        VariantModelHandlers.register(V4);
        VariantModelHandlers.register(V9);
        VariantModelHandlers.register(V16);
        VariantModelHandlers.register(R4);
        VariantModelHandlers.register(R9);
        VariantModelHandlers.register(R16);
        VariantModelHandlers.register(AR);
        VariantModelHandlers.register(MULTI_LAYER_LAVA_AR);
        VariantModelHandlers.register(MULTI_LAYER_WATER_AR);
        VariantModelHandlers.register(MULTIBLOCK_2X2);
        VariantModelHandlers.register(MULTIBLOCK_3X3);
        VariantModelHandlers.register(MULTIBLOCK_4X4);
        VariantModelHandlers.register(MULTI_LAYER_WATER_2X2);
        VariantModelHandlers.register(MULTI_LAYER_WATER_3X3);
        VariantModelHandlers.register(MULTI_LAYER_WATER_4X4);
        VariantModelHandlers.register(REDSTONE_LAMP);
        VariantModelHandlers.register(GLASS);
        VariantModelHandlers.register(ICE);
        VariantModelHandlers.register(ICE_2X2);
        VariantModelHandlers.register(ICE_3X3);
        VariantModelHandlers.register(ICE_4X4);
        VariantModelHandlers.register(ICE_AR);
    }
}
