package io.github.chiselteam.chisel.registry;

import io.github.chiselteam.chisel.core.variant.VariantModelHandler;
import io.github.chiselteam.chisel.core.variant.VariantModelHandlers;
import io.github.chiselteam.chisel.core.variant.VariantModels;
import io.github.chiselteam.chisel.core.variant.handler.*;

public class ChiselModelHandlers {
    private static final VariantModels MODELS = new VariantModels();

    public static final VariantModelHandler CUBE_ALL = new CubeAllVariantModelHandler("cube_all", MODELS.CUBE_ALL);
    public static final VariantModelHandler SHADELESS = new CubeAllVariantModelHandler("shadeless", MODELS.SHADELESS);
    public static final VariantModelHandler PILLAR = new CubeAllVariantModelHandler("pillar", MODELS.PILLAR);
    public static final VariantModelHandler BOOKSHELF = new DirectionalCTMVariantModelHandler("bookshelf", MODELS.BOOKSHELF, true);
    public static final VariantModelHandler TBS = new CubeAllVariantModelHandler("top_bottom_side", MODELS.TOP_BOTTOM_SIDE);
    public static final VariantModelHandler CONNECTED = new CTMVariantModelHandler("connected", MODELS.CTM);
    public static final VariantModelHandler CONNECTED_TBS = new TBSCTMVariantModelHandler("connected_tbs", MODELS.CTM_TBS);
    public static final VariantModelHandler CTMV = new DirectionalCTMVariantModelHandler("ctmv", MODELS.CTMV, false);
    public static final VariantModelHandler CTMH = new DirectionalCTMVariantModelHandler("ctmh", MODELS.CTMH, false);
    public static final VariantModelHandler MULTI_LAYER = new CubeAllVariantModelHandler("multi_layer", MODELS.MULTI_LAYER);
    public static final VariantModelHandler MULTI_LAYER_TBS = new CubeAllVariantModelHandler("multi_layer_tbs", MODELS.MULTI_LAYER_TBS);
    public static final VariantModelHandler MULTI_LAYER_TBS_TINTED = new CubeAllVariantModelHandler("multi_layer_tbs_tinted", MODELS.MULTI_LAYER_TBS_TINTED);
    public static final VariantModelHandler MULTI_LAYER_LAVA = new CubeAllVariantModelHandler("multi_layer_lava", MODELS.LAVASTONE);
    public static final VariantModelHandler MULTI_LAYER_LAVA_TOP_BOTTOM_SIDE = new CubeAllVariantModelHandler("multi_layer_lava_top_bottom_side", MODELS.LAVASTONE_TOP_BOTTOM_SIDE);
    public static final VariantModelHandler LAVA_2x2 = new MultiblockCTMVariantModelHandler("lava_2x2", MODELS.LAVASTONE_2X2, false, 2, true);
    public static final VariantModelHandler LAVA_3x3 = new MultiblockCTMVariantModelHandler("lava_3x3", MODELS.LAVASTONE_3X3, false, 3, true);
    public static final VariantModelHandler LAVA_4x4 = new MultiblockCTMVariantModelHandler("lava_4x4", MODELS.LAVASTONE_4X4, false, 4, true);
    public static final VariantModelHandler MULTI_LAYER_WATER = new CubeAllVariantModelHandler("multi_layer_water", MODELS.WATERSTONE);
    public static final VariantModelHandler MULTI_LAYER_CONNECTED = new CTMVariantModelHandler("multi_layer_connected", MODELS.MULTI_LAYER_CTM, true);
    public static final VariantModelHandler MULTI_LAYER_CONNECTED_TINTED = new CTMVariantModelHandler("multi_layer_connected_tinted", MODELS.MULTI_LAYER_CTM_TINTED, true);
    public static final VariantModelHandler MULTI_LAYER_CONNECTED_GLOW = new CTMVariantModelHandler("multi_layer_connected_glow", MODELS.MULTI_LAYER_CTM_GLOW);
    public static final VariantModelHandler ANTIBLOCK = new CTMVariantModelHandler("antiblock", MODELS.ANTIBLOCK);
    public static final VariantModelHandler LAYERED_MULTI_LAYER_CONNECTED_GLOW = new CTMVariantModelHandler("layered_multi_layer_connected_glow", MODELS.LAYERED_MULTI_LAYER_CTM_GLOW);
    public static final VariantModelHandler CARPET = new CubeAllVariantModelHandler("carpet", MODELS.CARPET);
    public static final VariantModelHandler IRON_BARS = new CubeAllVariantModelHandler("iron_bars", MODELS.IRON_BARS);
    public static final VariantModelHandler GLASS_PANE = new CubeAllVariantModelHandler("glass_pane", MODELS.GLASS_PANE);
    public static final VariantModelHandler MOSSY = new CubeAllVariantModelHandler("mossy", MODELS.MOSSY);
    public static final VariantModelHandler MOSSY_TOP_BOTTOM_SIDE = new CubeAllVariantModelHandler("mossy_top_bottom_side", MODELS.MOSSY_TOP_BOTTOM_SIDE);
    public static final VariantModelHandler PUMPKIN = new CubeAllVariantModelHandler("pumpkin", MODELS.PUMPKIN);
    public static final VariantModelHandler TORCH = new CubeAllVariantModelHandler("torch", MODELS.TORCH);
    public static final VariantModelHandler WALL_TORCH = new WallTorchVariantModelHandler("wall_torch", MODELS.WALL_TORCH);
    public static final VariantModelHandler ROAD_LINES = new CubeAllVariantModelHandler("road_lines", MODELS.ROAD_LINES);
    public static final VariantModelHandler V4 = new MultiblockCTMVariantModelHandler("v4", MODELS.V4, false, 2, false);
    public static final VariantModelHandler V9 = new MultiblockCTMVariantModelHandler("v9", MODELS.V9, false, 3, false);
    public static final VariantModelHandler V16 = new MultiblockCTMVariantModelHandler("v16", MODELS.V16, false, 4, false);
    public static final VariantModelHandler R4 = new MultiblockCTMVariantModelHandler("r4", MODELS.R4, true, 2, false);
    public static final VariantModelHandler R9 = new MultiblockCTMVariantModelHandler("r9", MODELS.R9, true, 3, false);
    public static final VariantModelHandler R16 = new MultiblockCTMVariantModelHandler("r16", MODELS.R16, true, 4, false);
    public static final VariantModelHandler AR = new ARVariantModelHandler("ar", MODELS.AR);
    public static final VariantModelHandler MULTI_LAYER_LAVA_AR = new ARVariantModelHandler("multi_layer_lava_ar", MODELS.LAVASTONE_AR, true);
    public static final VariantModelHandler MULTI_LAYER_WATER_AR = new ARVariantModelHandler("multi_layer_water_ar", MODELS.WATERSTONE_AR, true);
    public static final VariantModelHandler MULTIBLOCK_2X2 = new MultiblockCTMVariantModelHandler("multiblock_2x2", MODELS.MULTIBLOCK_2X2, false, 2, false);
    public static final VariantModelHandler MULTIBLOCK_3X3 = new MultiblockCTMVariantModelHandler("multiblock_3x3", MODELS.MULTIBLOCK_3X3, false, 3, false);
    public static final VariantModelHandler MULTIBLOCK_4X4 = new MultiblockCTMVariantModelHandler("multiblock_4x4", MODELS.MULTIBLOCK_4X4, false, 4, false);
    public static final VariantModelHandler MULTI_LAYER_WATER_2X2 = new MultiblockCTMVariantModelHandler("multi_layer_water_2x2", MODELS.WATERSTONE_2X2, false, 2, true);
    public static final VariantModelHandler MULTI_LAYER_WATER_3X3 = new MultiblockCTMVariantModelHandler("multi_layer_water_3x3", MODELS.WATERSTONE_3X3, false, 3, true);
    public static final VariantModelHandler MULTI_LAYER_WATER_4X4 = new MultiblockCTMVariantModelHandler("multi_layer_water_4x4", MODELS.WATERSTONE_4X4, false, 4, true);
    public static final VariantModelHandler REDSTONE_LAMP = new CubeAllVariantModelHandler("redstone_lamp", MODELS.REDSTONE_LAMP);

    public static void registerAll() {
        VariantModelHandlers.register(CUBE_ALL);
        VariantModelHandlers.register(SHADELESS);
        VariantModelHandlers.register(PILLAR);
        VariantModelHandlers.register(BOOKSHELF);
        VariantModelHandlers.register(TBS);
        VariantModelHandlers.register(CONNECTED);
        VariantModelHandlers.register(CONNECTED_TBS);
        VariantModelHandlers.register(CTMV);
        VariantModelHandlers.register(CTMH);
        VariantModelHandlers.register(MULTI_LAYER);
        VariantModelHandlers.register(MULTI_LAYER_TBS);
        VariantModelHandlers.register(MULTI_LAYER_TBS_TINTED);
        VariantModelHandlers.register(MULTI_LAYER_LAVA);
        VariantModelHandlers.register(MULTI_LAYER_LAVA_TOP_BOTTOM_SIDE);
        VariantModelHandlers.register(LAVA_2x2);
        VariantModelHandlers.register(LAVA_3x3);
        VariantModelHandlers.register(LAVA_4x4);
        VariantModelHandlers.register(MULTI_LAYER_WATER);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED_TINTED);
        VariantModelHandlers.register(MULTI_LAYER_CONNECTED_GLOW);
        VariantModelHandlers.register(LAYERED_MULTI_LAYER_CONNECTED_GLOW);
        VariantModelHandlers.register(CARPET);
        VariantModelHandlers.register(IRON_BARS);
        VariantModelHandlers.register(GLASS_PANE);
        VariantModelHandlers.register(MOSSY);
        VariantModelHandlers.register(MOSSY_TOP_BOTTOM_SIDE);
        VariantModelHandlers.register(PUMPKIN);
        VariantModelHandlers.register(TORCH);
        VariantModelHandlers.register(WALL_TORCH);
        VariantModelHandlers.register(ROAD_LINES);
        VariantModelHandlers.register(V4);
        VariantModelHandlers.register(V9);
        VariantModelHandlers.register(V16);
        VariantModelHandlers.register(R4);
        VariantModelHandlers.register(R9);
        VariantModelHandlers.register(R16);
        VariantModelHandlers.register(AR);
        VariantModelHandlers.register(MULTI_LAYER_LAVA_AR);
        VariantModelHandlers.register(MULTI_LAYER_WATER_AR);
        VariantModelHandlers.register(MULTIBLOCK_2X2);
        VariantModelHandlers.register(MULTIBLOCK_3X3);
        VariantModelHandlers.register(MULTIBLOCK_4X4);
        VariantModelHandlers.register(MULTI_LAYER_WATER_2X2);
        VariantModelHandlers.register(MULTI_LAYER_WATER_3X3);
        VariantModelHandlers.register(MULTI_LAYER_WATER_4X4);
        VariantModelHandlers.register(REDSTONE_LAMP);
    }
}
