package chisel.registry.blocks;

import chisel.block.ConnectedTextureCarpetBlock;
import chisel.util.ChiselBlocksProvider;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.neoforge.registries.DeferredBlock;

public class ChiselOtherBlocks extends ChiselBlocksProvider {

    public static DeferredBlock<Block> ANTIBLOCK_BLACK;
    public static DeferredBlock<Block> ANTIBLOCK_BLUE;
    public static DeferredBlock<Block> ANTIBLOCK_BROWN;
    public static DeferredBlock<Block> ANTIBLOCK_CYAN;
    public static DeferredBlock<Block> ANTIBLOCK_GRAY;
    public static DeferredBlock<Block> ANTIBLOCK_GREEN;
    public static DeferredBlock<Block> ANTIBLOCK_LIGHT_BLUE;
    public static DeferredBlock<Block> ANTIBLOCK_LIGHT_GRAY;
    public static DeferredBlock<Block> ANTIBLOCK_LIME;
    public static DeferredBlock<Block> ANTIBLOCK_MAGENTA;
    public static DeferredBlock<Block> ANTIBLOCK_ORANGE;
    public static DeferredBlock<Block> ANTIBLOCK_PINK;
    public static DeferredBlock<Block> ANTIBLOCK_PURPLE;
    public static DeferredBlock<Block> ANTIBLOCK_RED;
    public static DeferredBlock<Block> ANTIBLOCK_WHITE;
    public static DeferredBlock<Block> ANTIBLOCK_YELLOW;

    public static DeferredBlock<Block> CARPET_0;
    public static DeferredBlock<Block> CARPET_1;
    public static DeferredBlock<Block> CARPET_2;
    public static DeferredBlock<Block> CARPET_3;
    public static DeferredBlock<Block> CARPET_4;
    public static DeferredBlock<Block> CARPET_5;
    public static DeferredBlock<Block> CARPET_6;
    public static DeferredBlock<Block> CARPET_7;
    public static DeferredBlock<Block> CARPET_8;
    public static DeferredBlock<Block> CARPET_9;
    public static DeferredBlock<Block> CARPET_10;
    public static DeferredBlock<Block> CARPET_11;
    public static DeferredBlock<Block> CARPET_12;
    public static DeferredBlock<Block> CARPET_13;
    public static DeferredBlock<Block> CARPET_14;
    public static DeferredBlock<Block> CARPET_15;

    public static DeferredBlock<Block> CARPET_FLOOR_0;
    public static DeferredBlock<Block> CARPET_FLOOR_1;
    public static DeferredBlock<Block> CARPET_FLOOR_2;
    public static DeferredBlock<Block> CARPET_FLOOR_3;
    public static DeferredBlock<Block> CARPET_FLOOR_4;
    public static DeferredBlock<Block> CARPET_FLOOR_5;
    public static DeferredBlock<Block> CARPET_FLOOR_6;
    public static DeferredBlock<Block> CARPET_FLOOR_7;
    public static DeferredBlock<Block> CARPET_FLOOR_8;
    public static DeferredBlock<Block> CARPET_FLOOR_9;
    public static DeferredBlock<Block> CARPET_FLOOR_10;
    public static DeferredBlock<Block> CARPET_FLOOR_11;
    public static DeferredBlock<Block> CARPET_FLOOR_12;
    public static DeferredBlock<Block> CARPET_FLOOR_13;
    public static DeferredBlock<Block> CARPET_FLOOR_14;
    public static DeferredBlock<Block> CARPET_FLOOR_15;

    public static DeferredBlock<Block> CLOUD_GRID;
    public static DeferredBlock<Block> CLOUD_LARGE;
    public static DeferredBlock<Block> CLOUD_NORMAL;
    public static DeferredBlock<Block> CLOUD_SMALL;
    public static DeferredBlock<Block> CLOUD_VERTICAL;

    public static DeferredBlock<Block> DIAMOND_BISMUTH;
    public static DeferredBlock<Block> DIAMOND_CELLS;
    public static DeferredBlock<Block> DIAMOND_CRUSHED;
    public static DeferredBlock<Block> DIAMOND_EMBOSSED;
    public static DeferredBlock<Block> DIAMOND_OBSIDIAN;
    public static DeferredBlock<Block> DIAMOND_OBSIDIAN_PURPLE;
    public static DeferredBlock<Block> DIAMOND_ORNATE;
    public static DeferredBlock<Block> DIAMOND_PANEL;
    public static DeferredBlock<Block> DIAMOND_SIMPLE;
    public static DeferredBlock<Block> DIAMOND_SMALL_BLOCKS;
    public static DeferredBlock<Block> DIAMOND_SMALL_BLOCKS_ORNATE;
    public static DeferredBlock<Block> DIAMOND_ZELDA;

    public static DeferredBlock<Block> DIRT_BRICKS;
    public static DeferredBlock<Block> DIRT_BRICKS_ARRANGED;
    public static DeferredBlock<Block> DIRT_BRICKS_DISARRAY;
    public static DeferredBlock<Block> DIRT_BRICKS_LARGE;
    public static DeferredBlock<Block> DIRT_CHUNKY;
    public static DeferredBlock<Block> DIRT_COBBLE;
    public static DeferredBlock<Block> DIRT_HAPPY;
    public static DeferredBlock<Block> DIRT_HORIZONTAL;
    public static DeferredBlock<Block> DIRT_LAYERS;
    public static DeferredBlock<Block> DIRT_NETHERBRICKS;
    public static DeferredBlock<Block> DIRT_PLATE;
    public static DeferredBlock<Block> DIRT_REINFORCED;
    public static DeferredBlock<Block> DIRT_REINFORCED_COBBLE;
    public static DeferredBlock<Block> DIRT_VERT;
    public static DeferredBlock<Block> DIRT_VERTICAL;

    public static DeferredBlock<Block> EMERALD_BISMUTH;
    public static DeferredBlock<Block> EMERALD_BLOCKS_SMALL;
    public static DeferredBlock<Block> EMERALD_BLOCKS_SMALL_ORNATE;
    public static DeferredBlock<Block> EMERALD_CELL;
    public static DeferredBlock<Block> EMERALD_CHUNK;
    public static DeferredBlock<Block> EMERALD_CIRCLE;
    public static DeferredBlock<Block> EMERALD_MASONRY;
    public static DeferredBlock<Block> EMERALD_ORNATE;
    public static DeferredBlock<Block> EMERALD_ORNATE_LAYER;
    public static DeferredBlock<Block> EMERALD_PANEL;
    public static DeferredBlock<Block> EMERALD_PANEL_CLASSIC;
    public static DeferredBlock<Block> EMERALD_PRISMATIC;
    public static DeferredBlock<Block> EMERALD_SMOOTH;
    public static DeferredBlock<Block> EMERALD_ZELDA;

    public static DeferredBlock<Block> GLASS_BORDERLESS;
    public static DeferredBlock<Block> GLASS_BUBBLE;
    public static DeferredBlock<Block> GLASS_CHINESE;
    public static DeferredBlock<Block> GLASS_CHINESE_2;
    public static DeferredBlock<Block> GLASS_CHRONO;
    public static DeferredBlock<Block> GLASS_DUNGEON;
    public static DeferredBlock<Block> GLASS_EDGE;
    public static DeferredBlock<Block> GLASS_EDGE_STEEL;
    public static DeferredBlock<Block> GLASS_FENCE;
    public static DeferredBlock<Block> GLASS_GRID_THICK;
    public static DeferredBlock<Block> GLASS_GRID_THIN;
    public static DeferredBlock<Block> GLASS_JAPANESE;
    public static DeferredBlock<Block> GLASS_JAPANESE_2;
    public static DeferredBlock<Block> GLASS_LIGHT;
    public static DeferredBlock<Block> GLASS_ORNATE;
    public static DeferredBlock<Block> GLASS_ORNATE_OLD;
    public static DeferredBlock<Block> GLASS_SCREEN;
    public static DeferredBlock<Block> GLASS_SHALE;
    public static DeferredBlock<Block> GLASS_STEEL;
    public static DeferredBlock<Block> GLASS_STONE;

    public static DeferredBlock<Block> GLASS_PANE_BORDERLESS;
    public static DeferredBlock<Block> GLASS_PANE_BUBBLE;
    public static DeferredBlock<Block> GLASS_PANE_CHINESE;
    public static DeferredBlock<Block> GLASS_PANE_CHINESE_GOLD;
    public static DeferredBlock<Block> GLASS_PANE_JAPANESE_TILES;
    public static DeferredBlock<Block> GLASS_PANE_JAPANESE_TRADITIONAL;
    public static DeferredBlock<Block> GLASS_PANE_SCREEN;
    public static DeferredBlock<Block> GLASS_PANE_STREAK;

    public static DeferredBlock<Block> GLOWSTONE_ARRAY;
    public static DeferredBlock<Block> GLOWSTONE_BISMUTH;
    public static DeferredBlock<Block> GLOWSTONE_BRAID;
    public static DeferredBlock<Block> GLOWSTONE_CHAOTIC_MEDIUM;
    public static DeferredBlock<Block> GLOWSTONE_CHAOTIC_SMALL;
    public static DeferredBlock<Block> GLOWSTONE_CIRCULAR;
    public static DeferredBlock<Block> GLOWSTONE_CRACKED;
    public static DeferredBlock<Block> GLOWSTONE_CRACKED_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_DENT;
    public static DeferredBlock<Block> GLOWSTONE_ENCASED_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_FRENCH_1;
    public static DeferredBlock<Block> GLOWSTONE_FRENCH_2;
    public static DeferredBlock<Block> GLOWSTONE_JELLYBEAN;
    public static DeferredBlock<Block> GLOWSTONE_LAYERS;
    public static DeferredBlock<Block> GLOWSTONE_MOSAIC;
    public static DeferredBlock<Block> GLOWSTONE_NEON;
    public static DeferredBlock<Block> GLOWSTONE_NEON_PANEL;
    public static DeferredBlock<Block> GLOWSTONE_ORNATE;
    public static DeferredBlock<Block> GLOWSTONE_PANEL;
    public static DeferredBlock<Block> GLOWSTONE_PILLAR;
    public static DeferredBlock<Block> GLOWSTONE_PRISM;
    public static DeferredBlock<Block> GLOWSTONE_ROAD;
    public static DeferredBlock<Block> GLOWSTONE_SLANTED;
    public static DeferredBlock<Block> GLOWSTONE_SMALL_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_SOFT_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_SOLID_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_TILES_LARGE;
    public static DeferredBlock<Block> GLOWSTONE_TILES_LARGE_BISMUTH;
    public static DeferredBlock<Block> GLOWSTONE_TILES_MEDIUM;
    public static DeferredBlock<Block> GLOWSTONE_TILES_SMALL;
    public static DeferredBlock<Block> GLOWSTONE_TRIPLE_BRICKS;
    public static DeferredBlock<Block> GLOWSTONE_TWISTED;

    public static DeferredBlock<Block> ICE_BISMUTH;
    public static DeferredBlock<Block> ICE_BRICKS_LARGE;
    public static DeferredBlock<Block> ICE_BRICKS_SMALL;
    public static DeferredBlock<Block> ICE_COBBLE;
    public static DeferredBlock<Block> ICE_DOUBLE_SLAB;
    public static DeferredBlock<Block> ICE_GLASS_WALL;
    public static DeferredBlock<Block> ICE_PANEL;
    public static DeferredBlock<Block> ICE_POISON;
    public static DeferredBlock<Block> ICE_ROUGH;
    public static DeferredBlock<Block> ICE_ROUGH_LARGE;
    public static DeferredBlock<Block> ICE_TILES_DISORDERED;
    public static DeferredBlock<Block> ICE_TILES_FANCY;
    public static DeferredBlock<Block> ICE_TILES_LARGE;
    public static DeferredBlock<Block> ICE_TILES_SUNKEN;
    public static DeferredBlock<Block> ICE_ZELDA;

    public static DeferredBlock<Block> ICE_PILLAR_PLAIN_PLAIN;
    public static DeferredBlock<Block> ICE_PILLAR_PLAIN_GREEK;
    public static DeferredBlock<Block> ICE_PILLAR_GREEK_PLAIN;
    public static DeferredBlock<Block> ICE_PILLAR_GREEK_GREEK;
    public static DeferredBlock<Block> ICE_PILLAR_CARVED;
    public static DeferredBlock<Block> ICE_PILLAR_ORNAMENTAL;
    public static DeferredBlock<Block> ICE_PILLAR_INSCRIBED;

    public static DeferredBlock<Block> IRON_BARS_CAGE;
    public static DeferredBlock<Block> IRON_BARS_GRID_THICK;
    public static DeferredBlock<Block> IRON_BARS_GRID_THIN;
    public static DeferredBlock<Block> IRON_BARS_MENACING;
    public static DeferredBlock<Block> IRON_BARS_MENACING_SPIKES;
    public static DeferredBlock<Block> IRON_BARS_NO_FRAME;
    public static DeferredBlock<Block> IRON_BARS_ORNATE;
    public static DeferredBlock<Block> IRON_BARS_SPIKES;
    public static DeferredBlock<Block> IRON_BARS_VERTICAL;

    public static DeferredBlock<Block> LAPIS_CHUNKY;
    public static DeferredBlock<Block> LAPIS_DARK;
    public static DeferredBlock<Block> LAPIS_ORNATE;
    public static DeferredBlock<Block> LAPIS_ORNATE_LAYER;
    public static DeferredBlock<Block> LAPIS_PANEL;
    public static DeferredBlock<Block> LAPIS_SMOOTH;
    public static DeferredBlock<Block> LAPIS_TILE;
    public static DeferredBlock<Block> LAPIS_ZELDA;

    public static DeferredBlock<Block> LEAVES_CHRISTMAS_BALLS;
    public static DeferredBlock<Block> LEAVES_CHRISTMAS_LIGHTS;
    public static DeferredBlock<Block> LEAVES_DEAD;
    public static DeferredBlock<Block> LEAVES_FANCY;
    public static DeferredBlock<Block> LEAVES_PINK;
    public static DeferredBlock<Block> LEAVES_RED;
    public static DeferredBlock<Block> LEAVES_WHITE;

    public static DeferredBlock<Block> LITPUMPKIN_0;
    public static DeferredBlock<Block> LITPUMPKIN_1;
    public static DeferredBlock<Block> LITPUMPKIN_2;
    public static DeferredBlock<Block> LITPUMPKIN_3;
    public static DeferredBlock<Block> LITPUMPKIN_4;
    public static DeferredBlock<Block> LITPUMPKIN_5;
    public static DeferredBlock<Block> LITPUMPKIN_6;
    public static DeferredBlock<Block> LITPUMPKIN_7;
    public static DeferredBlock<Block> LITPUMPKIN_8;
    public static DeferredBlock<Block> LITPUMPKIN_9;
    public static DeferredBlock<Block> LITPUMPKIN_10;
    public static DeferredBlock<Block> LITPUMPKIN_11;
    public static DeferredBlock<Block> LITPUMPKIN_12;
    public static DeferredBlock<Block> LITPUMPKIN_13;
    public static DeferredBlock<Block> LITPUMPKIN_14;
    public static DeferredBlock<Block> LITPUMPKIN_15;
    public static DeferredBlock<Block> LITPUMPKIN_16;

    public static DeferredBlock<Block> PACKED_ICE_BISMUTH;
    public static DeferredBlock<Block> PACKED_ICE_BRICKS_LARGE;
    public static DeferredBlock<Block> PACKED_ICE_BRICKS_SMALL;
    public static DeferredBlock<Block> PACKED_ICE_COBBLE;
    public static DeferredBlock<Block> PACKED_ICE_DOUBLE_SLAB;
    public static DeferredBlock<Block> PACKED_ICE_GLASS_WALL;
    public static DeferredBlock<Block> PACKED_ICE_PANEL;
    public static DeferredBlock<Block> PACKED_ICE_POISON;
    public static DeferredBlock<Block> PACKED_ICE_ROUGH;
    public static DeferredBlock<Block> PACKED_ICE_ROUGH_LARGE;
    public static DeferredBlock<Block> PACKED_ICE_TILES_DISORDERED;
    public static DeferredBlock<Block> PACKED_ICE_TILES_FANCY;
    public static DeferredBlock<Block> PACKED_ICE_TILES_LARGE;
    public static DeferredBlock<Block> PACKED_ICE_TILES_SUNKEN;
    public static DeferredBlock<Block> PACKED_ICE_ZELDA;

    public static DeferredBlock<Block> PACKED_ICE_PILLAR_PLAIN_PLAIN;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_PLAIN_GREEK;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_GREEK_PLAIN;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_GREEK_GREEK;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_CARVED;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_ORNAMENTAL;
    public static DeferredBlock<Block> PACKED_ICE_PILLAR_INSCRIBED;

    public static DeferredBlock<Block> PAPERWALL_BOXED;
    public static DeferredBlock<Block> PAPERWALL_CROSSED;
    public static DeferredBlock<Block> PAPERWALL_DOOR;
    public static DeferredBlock<Block> PAPERWALL_FLORAL;
    public static DeferredBlock<Block> PAPERWALL_PLAIN;
    public static DeferredBlock<Block> PAPERWALL_SIX;
    public static DeferredBlock<Block> PAPERWALL_STRIKE_HORIZONTAL;
    public static DeferredBlock<Block> PAPERWALL_STRIKE_MIDDLE;
    public static DeferredBlock<Block> PAPERWALL_STRIKE_VERTICAL;

    public static DeferredBlock<Block> PAPERWALL_BLOCK_BOXED;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_CROSSED;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_DOOR;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_FLORAL;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_PLAIN;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_SIX;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_STRIKE_HORIZONTAL;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_STRIKE_MIDDLE;
    public static DeferredBlock<Block> PAPERWALL_BLOCK_STRIKE_VERTICAL;

    public static DeferredBlock<Block> PUMPKIN_0;
    public static DeferredBlock<Block> PUMPKIN_1;
    public static DeferredBlock<Block> PUMPKIN_2;
    public static DeferredBlock<Block> PUMPKIN_3;
    public static DeferredBlock<Block> PUMPKIN_4;
    public static DeferredBlock<Block> PUMPKIN_5;
    public static DeferredBlock<Block> PUMPKIN_6;
    public static DeferredBlock<Block> PUMPKIN_7;
    public static DeferredBlock<Block> PUMPKIN_8;
    public static DeferredBlock<Block> PUMPKIN_9;
    public static DeferredBlock<Block> PUMPKIN_10;
    public static DeferredBlock<Block> PUMPKIN_11;
    public static DeferredBlock<Block> PUMPKIN_12;
    public static DeferredBlock<Block> PUMPKIN_13;
    public static DeferredBlock<Block> PUMPKIN_14;
    public static DeferredBlock<Block> PUMPKIN_15;
    public static DeferredBlock<Block> PUMPKIN_16;

    public static DeferredBlock<Block> REDSTONE_BRICKS;
    public static DeferredBlock<Block> REDSTONE_BRICKS_CHAOTIC;
    public static DeferredBlock<Block> REDSTONE_BRICKS_SMALL;
    public static DeferredBlock<Block> REDSTONE_CHISELED;
    public static DeferredBlock<Block> REDSTONE_CIRCUIT;
    public static DeferredBlock<Block> REDSTONE_CIRCUIT_SUPAPLEX;
    public static DeferredBlock<Block> REDSTONE_GREEK;
    public static DeferredBlock<Block> REDSTONE_LARGE;
    public static DeferredBlock<Block> REDSTONE_PILLAR;
    public static DeferredBlock<Block> REDSTONE_SKULLS;
    public static DeferredBlock<Block> REDSTONE_SMALL;
    public static DeferredBlock<Block> REDSTONE_SMOOTH;
    public static DeferredBlock<Block> REDSTONE_TILES;
    public static DeferredBlock<Block> REDSTONE_TILES_ORNATE;
    public static DeferredBlock<Block> REDSTONE_ZELDA;

    public static DeferredBlock<Block> ROAD_LINES_WHITE;
    public static DeferredBlock<Block> ROAD_LINES_WHITE_DOUBLE;
    public static DeferredBlock<Block> ROAD_LINES_YELLOW;
    public static DeferredBlock<Block> ROAD_LINES_YELLOW_DOUBLE;

    public static DeferredBlock<Block> SANDSTONE_BLOCK;
    public static DeferredBlock<Block> SANDSTONE_BLOCKS;
    public static DeferredBlock<Block> SANDSTONE_BLOCKS_SMALL;
    public static DeferredBlock<Block> SANDSTONE_FADED;
    public static DeferredBlock<Block> SANDSTONE_MOSAIC;
    public static DeferredBlock<Block> SANDSTONE_PILLAR;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_BASE;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_CAPSTONE;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_CAPSTONE_SMOOTH;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_SMALL;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_SMALL_SMOOTH;
    public static DeferredBlock<Block> SANDSTONE_PILLAR_SMOOTH;
    public static DeferredBlock<Block> SANDSTONE_SMOOTH_FLAT;
    public static DeferredBlock<Block> SANDSTONE_STACKED;

    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_0;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_1;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_2;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_3;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_4;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_5;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_6;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_7;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_8;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_9;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_10;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_11;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_12;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_13;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_14;
    public static DeferredBlock<Block> SANDSTONE_SCRIBBLES_15;

    public static DeferredBlock<Block> SNAKESTONE_SAND_0;
    public static DeferredBlock<Block> SNAKESTONE_SAND_1;

    public static DeferredBlock<Block> SNAKESTONE_STONE_0;
    public static DeferredBlock<Block> SNAKESTONE_STONE_1;

    public static DeferredBlock<Block> STONE_BRICKS_DISORDERED;
    public static DeferredBlock<Block> STONE_BRICKS_DISORDERED_PANEL;
    public static DeferredBlock<Block> STONE_BRICKS_DISORDERED_SMALL;
    public static DeferredBlock<Block> STONE_BRICKS_FANCY;
    public static DeferredBlock<Block> STONE_BRICKS_FELSIC;
    public static DeferredBlock<Block> STONE_BRICKS_MAFIC;
    public static DeferredBlock<Block> STONE_BRICKS_NEUTRAL;
    public static DeferredBlock<Block> STONE_BRICKS_ORNATE;
    public static DeferredBlock<Block> STONE_BRICKS_ORNATE_LARGE;
    public static DeferredBlock<Block> STONE_BRICKS_PANEL;
    public static DeferredBlock<Block> STONE_BRICKS_PANEL_ORNATE;
    public static DeferredBlock<Block> STONE_BRICKS_PANEL_SUNKEN;
    public static DeferredBlock<Block> STONE_BRICKS_POISON;
    public static DeferredBlock<Block> STONE_BRICKS_SMALL;
    public static DeferredBlock<Block> STONE_BRICKS_WIDE;

    public static DeferredBlock<Block> TORCH_0;
    public static DeferredBlock<Block> TORCH_1;
    public static DeferredBlock<Block> TORCH_2;
    public static DeferredBlock<Block> TORCH_3;
    public static DeferredBlock<Block> TORCH_4;
    public static DeferredBlock<Block> TORCH_5;
    public static DeferredBlock<Block> TORCH_6;
    public static DeferredBlock<Block> TORCH_7;
    public static DeferredBlock<Block> TORCH_8;
    public static DeferredBlock<Block> TORCH_9;

    public static DeferredBlock<Block> VALENTINES_BLOCK;
    public static DeferredBlock<Block> VALENTINES_BRICKS;
    public static DeferredBlock<Block> VALENTINES_BUMPY;
    public static DeferredBlock<Block> VALENTINES_COBBLE;
    public static DeferredBlock<Block> VALENTINES_COMPANION;
    public static DeferredBlock<Block> VALENTINES_EMPTY;
    public static DeferredBlock<Block> VALENTINES_FIRE;
    public static DeferredBlock<Block> VALENTINES_HEART;
    public static DeferredBlock<Block> VALENTINES_HEART_GRAY;
    public static DeferredBlock<Block> VALENTINES_TILE;

    public static DeferredBlock<Block> WOOLEN_CLAY_0;
    public static DeferredBlock<Block> WOOLEN_CLAY_1;
    public static DeferredBlock<Block> WOOLEN_CLAY_2;
    public static DeferredBlock<Block> WOOLEN_CLAY_3;
    public static DeferredBlock<Block> WOOLEN_CLAY_4;
    public static DeferredBlock<Block> WOOLEN_CLAY_5;
    public static DeferredBlock<Block> WOOLEN_CLAY_6;
    public static DeferredBlock<Block> WOOLEN_CLAY_7;
    public static DeferredBlock<Block> WOOLEN_CLAY_8;
    public static DeferredBlock<Block> WOOLEN_CLAY_9;
    public static DeferredBlock<Block> WOOLEN_CLAY_10;
    public static DeferredBlock<Block> WOOLEN_CLAY_11;
    public static DeferredBlock<Block> WOOLEN_CLAY_12;
    public static DeferredBlock<Block> WOOLEN_CLAY_13;
    public static DeferredBlock<Block> WOOLEN_CLAY_14;
    public static DeferredBlock<Block> WOOLEN_CLAY_15;

    @Override
    public void registerBlocks() {
        ANTIBLOCK_BLACK = register("antiblock_black", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CONCRETE));
        ANTIBLOCK_BLUE = register("antiblock_blue", BlockBehaviour.Properties.ofFullCopy(Blocks.BLUE_CONCRETE));
        ANTIBLOCK_BROWN = register("antiblock_brown", BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_CONCRETE));
        ANTIBLOCK_CYAN = register("antiblock_cyan", BlockBehaviour.Properties.ofFullCopy(Blocks.CYAN_CONCRETE));
        ANTIBLOCK_GRAY = register("antiblock_gray", BlockBehaviour.Properties.ofFullCopy(Blocks.GRAY_CONCRETE));
        ANTIBLOCK_GREEN = register("antiblock_green", BlockBehaviour.Properties.ofFullCopy(Blocks.GREEN_CONCRETE));
        ANTIBLOCK_LIGHT_BLUE = register("antiblock_light_blue", BlockBehaviour.Properties.ofFullCopy(Blocks.LIGHT_BLUE_CONCRETE));
        ANTIBLOCK_LIGHT_GRAY = register("antiblock_light_gray", BlockBehaviour.Properties.ofFullCopy(Blocks.GRAY_CONCRETE));
        ANTIBLOCK_LIME = register("antiblock_lime", BlockBehaviour.Properties.ofFullCopy(Blocks.LIME_CONCRETE));
        ANTIBLOCK_MAGENTA = register("antiblock_magenta", BlockBehaviour.Properties.ofFullCopy(Blocks.MAGENTA_CONCRETE));
        ANTIBLOCK_ORANGE = register("antiblock_orange", BlockBehaviour.Properties.ofFullCopy(Blocks.ORANGE_CONCRETE));
        ANTIBLOCK_PINK = register("antiblock_pink", BlockBehaviour.Properties.ofFullCopy(Blocks.PINK_CONCRETE));
        ANTIBLOCK_PURPLE = register("antiblock_purple", BlockBehaviour.Properties.ofFullCopy(Blocks.PURPLE_CONCRETE));
        ANTIBLOCK_RED = register("antiblock_red", BlockBehaviour.Properties.ofFullCopy(Blocks.RED_CONCRETE));
        ANTIBLOCK_WHITE = register("antiblock_white", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_CONCRETE));
        ANTIBLOCK_YELLOW = register("antiblock_yellow", BlockBehaviour.Properties.ofFullCopy(Blocks.YELLOW_CONCRETE));

        CARPET_0 = register("carpet_0", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_CARPET));
        CARPET_1 = register("carpet_1", BlockBehaviour.Properties.ofFullCopy(Blocks.ORANGE_CARPET));
        CARPET_2 = register("carpet_2", BlockBehaviour.Properties.ofFullCopy(Blocks.MAGENTA_CARPET));
        CARPET_3 = register("carpet_3", BlockBehaviour.Properties.ofFullCopy(Blocks.LIGHT_BLUE_CARPET));
        CARPET_4 = register("carpet_4", BlockBehaviour.Properties.ofFullCopy(Blocks.YELLOW_CARPET));
        CARPET_5 = register("carpet_5", BlockBehaviour.Properties.ofFullCopy(Blocks.LIME_CARPET));
        CARPET_6 = register("carpet_6", BlockBehaviour.Properties.ofFullCopy(Blocks.PINK_CARPET));
        CARPET_7 = register("carpet_7", BlockBehaviour.Properties.ofFullCopy(Blocks.GRAY_CARPET));
        CARPET_8 = register("carpet_8", BlockBehaviour.Properties.ofFullCopy(Blocks.LIGHT_GRAY_CARPET));
        CARPET_9 = register("carpet_9", BlockBehaviour.Properties.ofFullCopy(Blocks.CYAN_CARPET));
        CARPET_10 = register("carpet_10", BlockBehaviour.Properties.ofFullCopy(Blocks.PURPLE_CARPET));
        CARPET_11 = register("carpet_11", BlockBehaviour.Properties.ofFullCopy(Blocks.BLUE_CARPET));
        CARPET_12 = register("carpet_12", BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_CARPET));
        CARPET_13 = register("carpet_13", BlockBehaviour.Properties.ofFullCopy(Blocks.GREEN_CARPET));
        CARPET_14 = register("carpet_14", BlockBehaviour.Properties.ofFullCopy(Blocks.RED_CARPET));
        CARPET_15 = register("carpet_15", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CARPET));

        CARPET_FLOOR_0 = register("carpet_floor_0", p -> new ConnectedTextureCarpetBlock(DyeColor.WHITE, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_CARPET));
        CARPET_FLOOR_1 = register("carpet_floor_1", p -> new ConnectedTextureCarpetBlock(DyeColor.ORANGE, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.ORANGE_CARPET));
        CARPET_FLOOR_2 = register("carpet_floor_2", p -> new ConnectedTextureCarpetBlock(DyeColor.MAGENTA, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.MAGENTA_CARPET));
        CARPET_FLOOR_3 = register("carpet_floor_3", p -> new ConnectedTextureCarpetBlock(DyeColor.LIGHT_BLUE, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.LIGHT_BLUE_CARPET));
        CARPET_FLOOR_4 = register("carpet_floor_4", p -> new ConnectedTextureCarpetBlock(DyeColor.YELLOW, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.YELLOW_CARPET));
        CARPET_FLOOR_5 = register("carpet_floor_5", p -> new ConnectedTextureCarpetBlock(DyeColor.LIME, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.LIME_CARPET));
        CARPET_FLOOR_6 = register("carpet_floor_6", p -> new ConnectedTextureCarpetBlock(DyeColor.PINK, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PINK_CARPET));
        CARPET_FLOOR_7 = register("carpet_floor_7", p -> new ConnectedTextureCarpetBlock(DyeColor.GRAY, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GRAY_CARPET));
        CARPET_FLOOR_8 = register("carpet_floor_8", p -> new ConnectedTextureCarpetBlock(DyeColor.LIGHT_GRAY, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.LIGHT_GRAY_CARPET));
        CARPET_FLOOR_9 = register("carpet_floor_9", p -> new ConnectedTextureCarpetBlock(DyeColor.CYAN, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.CYAN_CARPET));
        CARPET_FLOOR_10 = register("carpet_floor_10", p -> new ConnectedTextureCarpetBlock(DyeColor.PURPLE, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.PURPLE_CARPET));
        CARPET_FLOOR_11 = register("carpet_floor_11", p -> new ConnectedTextureCarpetBlock(DyeColor.BLUE, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BLUE_CARPET));
        CARPET_FLOOR_12 = register("carpet_floor_12", p -> new ConnectedTextureCarpetBlock(DyeColor.BROWN, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BROWN_CARPET));
        CARPET_FLOOR_13 = register("carpet_floor_13", p -> new ConnectedTextureCarpetBlock(DyeColor.GREEN, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.GREEN_CARPET));
        CARPET_FLOOR_14 = register("carpet_floor_14", p -> new ConnectedTextureCarpetBlock(DyeColor.RED, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.RED_CARPET));
        CARPET_FLOOR_15 = register("carpet_floor_15", p -> new ConnectedTextureCarpetBlock(DyeColor.BLACK, p), () -> BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CARPET));

        CLOUD_GRID = register("cloud_grid", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL).noOcclusion());
        CLOUD_LARGE = register("cloud_large", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL).noOcclusion());
        CLOUD_NORMAL = register("cloud_normal", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL).noOcclusion());
        CLOUD_SMALL = register("cloud_small", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL).noOcclusion());
        CLOUD_VERTICAL = register("cloud_vertical", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL).noOcclusion());

        DIAMOND_BISMUTH = register("diamond_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_CELLS = register("diamond_cells", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_CRUSHED = register("diamond_crushed", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_EMBOSSED = register("diamond_embossed", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_OBSIDIAN = register("diamond_obsidian", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_OBSIDIAN_PURPLE = register("diamond_obsidian_purple", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_ORNATE = register("diamond_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_PANEL = register("diamond_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_SIMPLE = register("diamond_simple", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_SMALL_BLOCKS = register("diamond_small_blocks", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_SMALL_BLOCKS_ORNATE = register("diamond_small_blocks_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));
        DIAMOND_ZELDA = register("diamond_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK));

        DIRT_BRICKS = register("dirt_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_BRICKS_ARRANGED = register("dirt_bricks_arranged", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_BRICKS_DISARRAY = register("dirt_bricks_disarray", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_BRICKS_LARGE = register("dirt_bricks_large", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_CHUNKY = register("dirt_chunky", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_COBBLE = register("dirt_cobble", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_HAPPY = register("dirt_happy", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_HORIZONTAL = register("dirt_horizontal", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_LAYERS = register("dirt_layers", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_NETHERBRICKS = register("dirt_netherbricks", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_PLATE = register("dirt_plate", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_REINFORCED = register("dirt_reinforced", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_REINFORCED_COBBLE = register("dirt_reinforced_cobble", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_VERT = register("dirt_vert", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));
        DIRT_VERTICAL = register("dirt_vertical", BlockBehaviour.Properties.ofFullCopy(Blocks.DIRT));

        EMERALD_BISMUTH = register("emerald_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_BLOCKS_SMALL = register("emerald_blocks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_BLOCKS_SMALL_ORNATE = register("emerald_blocks_small_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_CELL = register("emerald_cell", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_CHUNK = register("emerald_chunk", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_CIRCLE = register("emerald_circle", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_MASONRY = register("emerald_masonry", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_ORNATE = register("emerald_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_ORNATE_LAYER = register("emerald_ornate_layer", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_PANEL = register("emerald_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_PANEL_CLASSIC = register("emerald_panel_classic", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_PRISMATIC = register("emerald_prismatic", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_SMOOTH = register("emerald_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));
        EMERALD_ZELDA = register("emerald_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.EMERALD_BLOCK));

        GLASS_BORDERLESS = register("glass_borderless", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_BUBBLE = register("glass_bubble", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_CHINESE = register("glass_chinese", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_CHINESE_2 = register("glass_chinese_2", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_CHRONO = register("glass_chrono", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_DUNGEON = register("glass_dungeon", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_EDGE = register("glass_edge", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_EDGE_STEEL = register("glass_edge_steel", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_FENCE = register("glass_fence", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_GRID_THICK = register("glass_grid_thick", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_GRID_THIN = register("glass_grid_thin", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_JAPANESE = register("glass_japanese", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_JAPANESE_2 = register("glass_japanese_2", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_LIGHT = register("glass_light", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_ORNATE = register("glass_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_ORNATE_OLD = register("glass_ornate_old", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_SCREEN = register("glass_screen", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_SHALE = register("glass_shale", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_STEEL = register("glass_steel", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));
        GLASS_STONE = register("glass_stone", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS));

        GLASS_PANE_BORDERLESS = register("glass_pane_borderless", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_BUBBLE = register("glass_pane_bubble", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_CHINESE = register("glass_pane_chinese", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_CHINESE_GOLD = register("glass_pane_chinese_gold", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_JAPANESE_TILES = register("glass_pane_japanese_tiles", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_JAPANESE_TRADITIONAL = register("glass_pane_japanese_traditional", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_SCREEN = register("glass_pane_screen", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));
        GLASS_PANE_STREAK = register("glass_pane_streak", BlockBehaviour.Properties.ofFullCopy(Blocks.GLASS_PANE));

        GLOWSTONE_ARRAY = register("glowstone_array", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_BISMUTH = register("glowstone_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_BRAID = register("glowstone_braid", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_CHAOTIC_MEDIUM = register("glowstone_chaotic_medium", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_CHAOTIC_SMALL = register("glowstone_chaotic_small", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_CIRCULAR = register("glowstone_circular", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_CRACKED = register("glowstone_cracked", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_CRACKED_BRICKS = register("glowstone_cracked_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_DENT = register("glowstone_dent", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_ENCASED_BRICKS = register("glowstone_encased_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_FRENCH_1 = register("glowstone_french_1", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_FRENCH_2 = register("glowstone_french_2", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_JELLYBEAN = register("glowstone_jellybean", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_LAYERS = register("glowstone_layers", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_MOSAIC = register("glowstone_mosaic", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_NEON = register("glowstone_neon", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_NEON_PANEL = register("glowstone_neon_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_ORNATE = register("glowstone_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_PANEL = register("glowstone_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_PILLAR = register("glowstone_pillar", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_PRISM = register("glowstone_prism", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_ROAD = register("glowstone_road", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_SLANTED = register("glowstone_slanted", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_SMALL_BRICKS = register("glowstone_small_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_SOFT_BRICKS = register("glowstone_soft_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_SOLID_BRICKS = register("glowstone_solid_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TILES_LARGE = register("glowstone_tiles_large", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TILES_LARGE_BISMUTH = register("glowstone_tiles_large_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TILES_MEDIUM = register("glowstone_tiles_medium", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TILES_SMALL = register("glowstone_tiles_small", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TRIPLE_BRICKS = register("glowstone_triple_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));
        GLOWSTONE_TWISTED = register("glowstone_twisted", BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE));

        ICE_BISMUTH = register("ice_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_BRICKS_LARGE = register("ice_bricks_large", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_BRICKS_SMALL = register("ice_bricks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_COBBLE = register("ice_cobble", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_DOUBLE_SLAB = register("ice_double_slab", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_GLASS_WALL = register("ice_glass_wall", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PANEL = register("ice_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_POISON = register("ice_poison", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_ROUGH = register("ice_rough", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_ROUGH_LARGE = register("ice_rough_large", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_TILES_DISORDERED = register("ice_tiles_disordered", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_TILES_FANCY = register("ice_tiles_fancy", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_TILES_LARGE = register("ice_tiles_large", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_TILES_SUNKEN = register("ice_tiles_sunken", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_ZELDA = register("ice_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));

        ICE_PILLAR_PLAIN_PLAIN = register("ice_pillar_plain_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_PLAIN_GREEK = register("ice_pillar_plain_greek", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_GREEK_PLAIN = register("ice_pillar_greek_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_GREEK_GREEK = register("ice_pillar_greek_greek", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_CARVED = register("ice_pillar_carved", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_ORNAMENTAL = register("ice_pillar_ornamental", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));
        ICE_PILLAR_INSCRIBED = register("ice_pillar_inscribed", BlockBehaviour.Properties.ofFullCopy(Blocks.ICE));

        IRON_BARS_CAGE = register("iron_bars_cage", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_GRID_THICK = register("iron_bars_grid_thick", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_GRID_THIN = register("iron_bars_grid_thin", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_MENACING = register("iron_bars_menacing", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_MENACING_SPIKES = register("iron_bars_menacing_spikes", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_NO_FRAME = register("iron_bars_no_frame", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_ORNATE = register("iron_bars_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_SPIKES = register("iron_bars_spikes", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));
        IRON_BARS_VERTICAL = register("iron_bars_vertical", BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_BARS));

        LAPIS_CHUNKY = register("lapis_chunky", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_DARK = register("lapis_dark", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_ORNATE = register("lapis_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_ORNATE_LAYER = register("lapis_ornate_layer", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_PANEL = register("lapis_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_SMOOTH = register("lapis_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_TILE = register("lapis_tile", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));
        LAPIS_ZELDA = register("lapis_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.LAPIS_BLOCK));

        LEAVES_CHRISTMAS_BALLS = register("leaf_christmas_balls", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_CHRISTMAS_LIGHTS = register("leaf_christmas_lights", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_DEAD = register("leaf_dead", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_FANCY = register("leaf_fancy", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_PINK = register("leaf_pink", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_RED = register("leaf_red", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));
        LEAVES_WHITE = register("leaf_white", BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_LEAVES));

        LITPUMPKIN_0 = register("lit_pumpkin_0", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_1 = register("lit_pumpkin_1", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_2 = register("lit_pumpkin_2", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_3 = register("lit_pumpkin_3", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_4 = register("lit_pumpkin_4", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_5 = register("lit_pumpkin_5", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_6 = register("lit_pumpkin_6", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_7 = register("lit_pumpkin_7", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_8 = register("lit_pumpkin_8", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_9 = register("lit_pumpkin_9", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_10 = register("lit_pumpkin_10", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_11 = register("lit_pumpkin_11", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_12 = register("lit_pumpkin_12", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_13 = register("lit_pumpkin_13", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_14 = register("lit_pumpkin_14", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_15 = register("lit_pumpkin_15", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));
        LITPUMPKIN_16 = register("lit_pumpkin_16", BlockBehaviour.Properties.ofFullCopy(Blocks.JACK_O_LANTERN));

        PACKED_ICE_BISMUTH = register("packed_ice_bismuth", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_BRICKS_LARGE = register("packed_ice_bricks_large", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_BRICKS_SMALL = register("packed_ice_bricks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_COBBLE = register("packed_ice_cobble", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_DOUBLE_SLAB = register("packed_ice_double_slab", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_GLASS_WALL = register("packed_ice_glass_wall", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PANEL = register("packed_ice_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_POISON = register("packed_ice_poison", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_ROUGH = register("packed_ice_rough", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_ROUGH_LARGE = register("packed_ice_rough_large", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_TILES_DISORDERED = register("packed_ice_tiles_disordered", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_TILES_FANCY = register("packed_ice_tiles_fancy", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_TILES_LARGE = register("packed_ice_tiles_large", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_TILES_SUNKEN = register("packed_ice_tiles_sunken", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_ZELDA = register("packed_ice_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));

        PACKED_ICE_PILLAR_PLAIN_PLAIN = register("packed_ice_pillar_plain_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_PLAIN_GREEK = register("packed_ice_pillar_plain_greek", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_GREEK_PLAIN = register("packed_ice_pillar_greek_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_GREEK_GREEK = register("packed_ice_pillar_greek_greek", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_CARVED = register("packed_ice_pillar_carved", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_ORNAMENTAL = register("packed_ice_pillar_ornamental", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));
        PACKED_ICE_PILLAR_INSCRIBED = register("packed_ice_pillar_inscribed", BlockBehaviour.Properties.ofFullCopy(Blocks.PACKED_ICE));

        PAPERWALL_BOXED = register("paperwall_boxed", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_CROSSED = register("paperwall_crossed", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_DOOR = register("paperwall_door", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_FLORAL = register("paperwall_floral", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_PLAIN = register("paperwall_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_SIX = register("paperwall_six", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_STRIKE_HORIZONTAL = register("paperwall_strike_horizontal", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_STRIKE_MIDDLE = register("paperwall_strike_middle", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_STRIKE_VERTICAL = register("paperwall_strike_vertical", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));

        PAPERWALL_BLOCK_BOXED = register("paperwall_block_boxed", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_CROSSED = register("paperwall_block_crossed", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_DOOR = register("paperwall_block_door", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_FLORAL = register("paperwall_block_floral", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_PLAIN = register("paperwall_block_plain", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_SIX = register("paperwall_block_six", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_STRIKE_HORIZONTAL = register("paperwall_block_strike_horizontal", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_STRIKE_MIDDLE = register("paperwall_block_strike_middle", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));
        PAPERWALL_BLOCK_STRIKE_VERTICAL = register("paperwall_block_strike_vertical", BlockBehaviour.Properties.ofFullCopy(Blocks.WHITE_WOOL));

        PUMPKIN_0 = register("pumpkin_0", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_1 = register("pumpkin_1", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_2 = register("pumpkin_2", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_3 = register("pumpkin_3", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_4 = register("pumpkin_4", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_5 = register("pumpkin_5", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_6 = register("pumpkin_6", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_7 = register("pumpkin_7", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_8 = register("pumpkin_8", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_9 = register("pumpkin_9", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_10 = register("pumpkin_10", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_11 = register("pumpkin_11", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_12 = register("pumpkin_12", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_13 = register("pumpkin_13", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_14 = register("pumpkin_14", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_15 = register("pumpkin_15", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));
        PUMPKIN_16 = register("pumpkin_16", BlockBehaviour.Properties.ofFullCopy(Blocks.CARVED_PUMPKIN));

        REDSTONE_BRICKS = register("redstone_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_BRICKS_CHAOTIC = register("redstone_bricks_chaotic", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_BRICKS_SMALL = register("redstone_bricks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_CHISELED = register("redstone_chiseled", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_CIRCUIT = register("redstone_circuit", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_CIRCUIT_SUPAPLEX = register("redstone_circuit_supaplex", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_GREEK = register("redstone_greek", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_LARGE = register("redstone_large", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_PILLAR = register("redstone_pillar", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_SKULLS = register("redstone_skulls", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_SMALL = register("redstone_small", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_SMOOTH = register("redstone_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_TILES = register("redstone_tiles", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_TILES_ORNATE = register("redstone_tiles_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));
        REDSTONE_ZELDA = register("redstone_zelda", BlockBehaviour.Properties.ofFullCopy(Blocks.REDSTONE_BLOCK));

        ROAD_LINES_WHITE = register("road_lines_white", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CONCRETE));
        ROAD_LINES_WHITE_DOUBLE = register("road_lines_white_double", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CONCRETE));
        ROAD_LINES_YELLOW = register("road_lines_yellow", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CONCRETE));
        ROAD_LINES_YELLOW_DOUBLE = register("road_lines_yellow_double", BlockBehaviour.Properties.ofFullCopy(Blocks.BLACK_CONCRETE));

        SANDSTONE_BLOCK = register("sandstone_block", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_BLOCKS = register("sandstone_blocks", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_BLOCKS_SMALL = register("sandstone_blocks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_FADED = register("sandstone_faded", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_MOSAIC = register("sandstone_mosaic", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR = register("sandstone_pillar", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_BASE = register("sandstone_pillar_base", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_CAPSTONE = register("sandstone_pillar_capstone", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_CAPSTONE_SMOOTH = register("sandstone_pillar_capstone_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_SMALL = register("sandstone_pillar_small", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_SMALL_SMOOTH = register("sandstone_pillar_small_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_PILLAR_SMOOTH = register("sandstone_pillar_smooth", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SMOOTH_FLAT = register("sandstone_smooth_flat", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_STACKED = register("sandstone_stacked", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));

        SANDSTONE_SCRIBBLES_0 = register("sandstone_scribbles_0", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_1 = register("sandstone_scribbles_1", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_2 = register("sandstone_scribbles_2", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_3 = register("sandstone_scribbles_3", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_4 = register("sandstone_scribbles_4", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_5 = register("sandstone_scribbles_5", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_6 = register("sandstone_scribbles_6", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_7 = register("sandstone_scribbles_7", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_8 = register("sandstone_scribbles_8", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_9 = register("sandstone_scribbles_9", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_10 = register("sandstone_scribbles_10", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_11 = register("sandstone_scribbles_11", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_12 = register("sandstone_scribbles_12", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_13 = register("sandstone_scribbles_13", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_14 = register("sandstone_scribbles_14", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SANDSTONE_SCRIBBLES_15 = register("sandstone_scribbles_15", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));

        SNAKESTONE_SAND_0 = register("snakestone_sand_0", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));
        SNAKESTONE_SAND_1 = register("snakestone_sand_1", BlockBehaviour.Properties.ofFullCopy(Blocks.SANDSTONE));

        SNAKESTONE_STONE_0 = register("snakestone_stone_0", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        SNAKESTONE_STONE_1 = register("snakestone_stone_1", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));

        STONE_BRICKS_DISORDERED = register("stone_bricks_disordered", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_DISORDERED_PANEL = register("stone_bricks_disordered_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_DISORDERED_SMALL = register("stone_bricks_disordered_small", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_FANCY = register("stone_bricks_fancy", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_FELSIC = register("stone_bricks_felsic", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_MAFIC = register("stone_bricks_mafic", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_NEUTRAL = register("stone_bricks_neutral", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_ORNATE = register("stone_bricks_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_ORNATE_LARGE = register("stone_bricks_ornate_large", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_PANEL = register("stone_bricks_panel", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_PANEL_ORNATE = register("stone_bricks_panel_ornate", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_PANEL_SUNKEN = register("stone_bricks_panel_sunken", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_POISON = register("stone_bricks_poison", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_SMALL = register("stone_bricks_small", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));
        STONE_BRICKS_WIDE = register("stone_bricks_wide", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS));

        TORCH_0 = register("torch_0", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_1 = register("torch_1", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_2 = register("torch_2", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_3 = register("torch_3", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_4 = register("torch_4", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_5 = register("torch_5", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_6 = register("torch_6", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_7 = register("torch_7", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_8 = register("torch_8", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));
        TORCH_9 = register("torch_9", BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH));

        VALENTINES_BLOCK = register("valentines_block", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_BRICKS = register("valentines_bricks", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_BUMPY = register("valentines_bumpy", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_COBBLE = register("valentines_cobble", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_COMPANION = register("valentines_companion", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_EMPTY = register("valentines_empty", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_FIRE = register("valentines_fire", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_HEART = register("valentines_heart", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_HEART_GRAY = register("valentines_heart_gray", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));
        VALENTINES_TILE = register("valentines_tile", BlockBehaviour.Properties.ofFullCopy(Blocks.STONE));

        WOOLEN_CLAY_0 = register("woolen_clay_0", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_1 = register("woolen_clay_1", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_2 = register("woolen_clay_2", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_3 = register("woolen_clay_3", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_4 = register("woolen_clay_4", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_5 = register("woolen_clay_5", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_6 = register("woolen_clay_6", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_7 = register("woolen_clay_7", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_8 = register("woolen_clay_8", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_9 = register("woolen_clay_9", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_10 = register("woolen_clay_10", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_11 = register("woolen_clay_11", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_12 = register("woolen_clay_12", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_13 = register("woolen_clay_13", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_14 = register("woolen_clay_14", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
        WOOLEN_CLAY_15 = register("woolen_clay_15", BlockBehaviour.Properties.ofFullCopy(Blocks.CLAY));
    }
}
